@props(['action', 'method' => 'POST', 'account' => null, 'accountClasses', 'accountTypes', 'parentAccounts', 'submitLabel'])

<form method="POST" action="{{ $action }}" class="max-w-5xl rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200">
    @csrf
    @if ($method !== 'POST') @method($method) @endif
    <div class="grid gap-4 md:grid-cols-2">
        <label class="flex flex-col gap-1 text-sm font-medium">Account code<input name="code" value="{{ old('code', $account?->code) }}" required maxlength="30" class="rounded-lg border border-slate-300 px-3 py-2">@error('code')<span class="text-red-700">{{ $message }}</span>@enderror</label>
        <label class="flex flex-col gap-1 text-sm font-medium">Account name<input name="name" value="{{ old('name', $account?->name) }}" required maxlength="255" class="rounded-lg border border-slate-300 px-3 py-2">@error('name')<span class="text-red-700">{{ $message }}</span>@enderror</label>
        <label class="flex flex-col gap-1 text-sm font-medium">Account class<select name="account_class" class="rounded-lg border border-slate-300 px-3 py-2">@foreach ($accountClasses as $class)<option value="{{ $class->value }}" @selected(old('account_class', $account?->account_class?->value) === $class->value)>{{ str($class->value)->headline() }}</option>@endforeach</select>@error('account_class')<span class="text-red-700">{{ $message }}</span>@enderror</label>
        <label class="flex flex-col gap-1 text-sm font-medium">Account type<select name="account_type" class="rounded-lg border border-slate-300 px-3 py-2">@foreach ($accountTypes as $type)<option value="{{ $type->value }}" @selected(old('account_type', $account?->account_type?->value) === $type->value)>{{ str($type->value)->headline() }}</option>@endforeach</select>@error('account_type')<span class="text-red-700">{{ $message }}</span>@enderror</label>
        <label class="flex flex-col gap-1 text-sm font-medium">Parent account<select name="parent_id" class="rounded-lg border border-slate-300 px-3 py-2"><option value="">None</option>@foreach ($parentAccounts as $parentAccount)<option value="{{ $parentAccount->id }}" @selected((string) old('parent_id', $account?->parent_id) === (string) $parentAccount->id)>{{ $parentAccount->code }} — {{ $parentAccount->name }}</option>@endforeach</select>@error('parent_id')<span class="text-red-700">{{ $message }}</span>@enderror</label>
        <label class="flex flex-col gap-1 text-sm font-medium">Display order<input type="number" min="0" name="display_order" value="{{ old('display_order', $account?->display_order ?? 0) }}" required class="rounded-lg border border-slate-300 px-3 py-2">@error('display_order')<span class="text-red-700">{{ $message }}</span>@enderror</label>
        <label class="flex items-center gap-2 text-sm font-medium"><input type="hidden" name="is_header" value="0"><input type="checkbox" name="is_header" value="1" @checked(old('is_header', $account?->is_header))>Header account</label>
        <label class="flex items-center gap-2 text-sm font-medium"><input type="hidden" name="is_postable" value="0"><input type="checkbox" name="is_postable" value="1" @checked(old('is_postable', $account?->is_postable ?? true))>Postable account</label>
        <label class="flex items-center gap-2 text-sm font-medium"><input type="hidden" name="is_control_account" value="0"><input type="checkbox" name="is_control_account" value="1" @checked(old('is_control_account', $account?->is_control_account))>Control account</label>
        <label class="flex flex-col gap-1 text-sm font-medium">Control account type<input name="control_account_type" value="{{ old('control_account_type', $account?->control_account_type) }}" maxlength="30" class="rounded-lg border border-slate-300 px-3 py-2">@error('control_account_type')<span class="text-red-700">{{ $message }}</span>@enderror</label>
        <label class="flex flex-col gap-1 text-sm font-medium md:col-span-2">Description<textarea name="description" rows="3" maxlength="2000" class="rounded-lg border border-slate-300 px-3 py-2">{{ old('description', $account?->description) }}</textarea>@error('description')<span class="text-red-700">{{ $message }}</span>@enderror</label>
    </div>
    <p class="mt-4 text-sm text-slate-500">Normal balance is derived from the account type. Header accounts cannot be postable.</p>
    <div class="mt-5 flex flex-wrap gap-3"><button class="rounded-lg bg-blue-700 px-4 py-2 text-sm font-semibold text-white">{{ $submitLabel }}</button><a href="{{ route('accounts.index') }}" class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold">Cancel</a></div>
</form>
