@props(['action', 'method' => 'POST', 'productService' => null, 'categories', 'unitsOfMeasure', 'submitLabel'])

<form method="POST" action="{{ $action }}" class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200">
    @csrf
    @if ($method !== 'POST') @method($method) @endif
    <div class="grid gap-4 md:grid-cols-2">
        <label class="flex flex-col gap-1 text-sm font-medium">SKU<input name="sku" value="{{ old('sku', $productService?->sku) }}" required maxlength="50" class="rounded-lg border border-slate-300 px-3 py-2">@error('sku')<span class="text-red-700">{{ $message }}</span>@enderror</label>
        <label class="flex flex-col gap-1 text-sm font-medium">Barcode (optional)<input name="barcode" value="{{ old('barcode', $productService?->barcode) }}" maxlength="100" class="rounded-lg border border-slate-300 px-3 py-2">@error('barcode')<span class="text-red-700">{{ $message }}</span>@enderror</label>
        <label class="flex flex-col gap-1 text-sm font-medium md:col-span-2">Name<input name="name" value="{{ old('name', $productService?->name) }}" required class="rounded-lg border border-slate-300 px-3 py-2">@error('name')<span class="text-red-700">{{ $message }}</span>@enderror</label>
        <label class="flex flex-col gap-1 text-sm font-medium md:col-span-2">Description<textarea name="description" rows="3" class="rounded-lg border border-slate-300 px-3 py-2">{{ old('description', $productService?->description) }}</textarea>@error('description')<span class="text-red-700">{{ $message }}</span>@enderror</label>
        <label class="flex flex-col gap-1 text-sm font-medium">Type<select name="type" class="rounded-lg border border-slate-300 px-3 py-2"><option value="product" @selected(old('type', $productService?->type ?? 'product') === 'product')>Product</option><option value="service" @selected(old('type', $productService?->type) === 'service')>Service</option></select>@error('type')<span class="text-red-700">{{ $message }}</span>@enderror</label>
        <label class="flex flex-col gap-1 text-sm font-medium">Category<select name="category_id" required class="rounded-lg border border-slate-300 px-3 py-2"><option value="">Select category</option>@foreach ($categories as $category)<option value="{{ $category->id }}" @selected((string) old('category_id', $productService?->category_id) === (string) $category->id)>{{ ucfirst($category->type) }} — {{ $category->name }}</option>@endforeach</select>@error('category_id')<span class="text-red-700">{{ $message }}</span>@enderror</label>
        <label class="flex flex-col gap-1 text-sm font-medium">Unit of measure<select name="unit_of_measure_id" required class="rounded-lg border border-slate-300 px-3 py-2"><option value="">Select unit</option>@foreach ($unitsOfMeasure as $unit)<option value="{{ $unit->id }}" @selected((string) old('unit_of_measure_id', $productService?->unit_of_measure_id) === (string) $unit->id)>{{ $unit->code }} — {{ $unit->name }}</option>@endforeach</select>@error('unit_of_measure_id')<span class="text-red-700">{{ $message }}</span>@enderror</label>
        <label class="flex flex-col gap-1 text-sm font-medium">Default cost<input type="number" min="0" step="0.0001" name="default_cost" value="{{ old('default_cost', $productService?->default_cost ?? '0.0000') }}" required class="rounded-lg border border-slate-300 px-3 py-2">@error('default_cost')<span class="text-red-700">{{ $message }}</span>@enderror</label>
        <label class="flex flex-col gap-1 text-sm font-medium">Selling price<input type="number" min="0" step="0.0001" name="selling_price" value="{{ old('selling_price', $productService?->selling_price ?? '0.0000') }}" required class="rounded-lg border border-slate-300 px-3 py-2">@error('selling_price')<span class="text-red-700">{{ $message }}</span>@enderror</label>
        <label class="flex flex-col gap-1 text-sm font-medium">Reorder level<input type="number" min="0" step="0.0001" name="reorder_level" value="{{ old('reorder_level', $productService?->reorder_level ?? '0.0000') }}" required class="rounded-lg border border-slate-300 px-3 py-2">@error('reorder_level')<span class="text-red-700">{{ $message }}</span>@enderror</label>
        <label class="flex items-center gap-2 self-end rounded-lg border border-slate-300 px-3 py-2 text-sm font-medium"><input type="hidden" name="is_inventory" value="0"><input type="checkbox" name="is_inventory" value="1" @checked(old('is_inventory', $productService?->is_inventory ?? false))>Track as inventory product</label>
        @error('is_inventory')<span class="text-sm text-red-700">{{ $message }}</span>@enderror
        <label class="flex flex-col gap-1 text-sm font-medium">Status<select name="status" class="rounded-lg border border-slate-300 px-3 py-2"><option value="active" @selected(old('status', $productService?->status ?? 'active') === 'active')>Active</option><option value="inactive" @selected(old('status', $productService?->status) === 'inactive')>Inactive</option></select>@error('status')<span class="text-red-700">{{ $message }}</span>@enderror</label>
    </div>
    <p class="mt-4 text-sm text-slate-500">Services cannot track inventory. Non-inventory items must use a zero reorder level.</p>
    <div class="mt-5 flex flex-wrap gap-3"><button class="rounded-lg bg-blue-700 px-4 py-2 text-sm font-semibold text-white">{{ $submitLabel }}</button><a href="{{ route('products-services.index') }}" class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold">Cancel</a></div>
</form>
