@props(['action', 'method' => 'POST', 'purchaseRequest' => null, 'requesters', 'items', 'suppliers', 'submitLabel'])
@php($formLines = old('lines', $purchaseRequest?->lines?->map(fn ($line) => ['product_service_id' => $line->product_service_id, 'preferred_supplier_id' => $line->preferred_supplier_id, 'description' => $line->description, 'uom_code' => $line->uom_code, 'uom_name' => $line->uom_name, 'quantity' => $line->quantity, 'estimated_unit_cost' => $line->estimated_unit_cost, 'notes' => $line->notes])->all() ?? [['product_service_id' => '', 'preferred_supplier_id' => '', 'description' => '', 'uom_code' => '', 'uom_name' => '', 'quantity' => '1.0000', 'estimated_unit_cost' => '0.0000', 'notes' => '']]))
<form method="POST" action="{{ $action }}" class="flex flex-col gap-5" data-line-form>
    @csrf @if($method !== 'POST') @method($method) @endif
    <section class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div class="grid gap-4 md:grid-cols-2">
        <label class="flex flex-col gap-1 text-sm font-medium">Request date<input type="date" name="request_date" value="{{ old('request_date', $purchaseRequest?->request_date?->toDateString() ?? now()->toDateString()) }}" required class="rounded-lg border border-slate-300 px-3 py-2">@error('request_date')<span class="text-red-700">{{ $message }}</span>@enderror</label>
        <label class="flex flex-col gap-1 text-sm font-medium">Requested by<select name="requested_by" required class="rounded-lg border border-slate-300 px-3 py-2"><option value="">Select requester</option>@foreach($requesters as $requester)<option value="{{ $requester->id }}" @selected((string)old('requested_by', $purchaseRequest?->requested_by ?? auth()->id()) === (string)$requester->id)>{{ $requester->name }}</option>@endforeach</select>@error('requested_by')<span class="text-red-700">{{ $message }}</span>@enderror</label>
        <label class="flex flex-col gap-1 text-sm font-medium">Needed by<input type="date" name="needed_by" value="{{ old('needed_by', $purchaseRequest?->needed_by?->toDateString()) }}" class="rounded-lg border border-slate-300 px-3 py-2">@error('needed_by')<span class="text-red-700">{{ $message }}</span>@enderror</label>
        <label class="flex flex-col gap-1 text-sm font-medium">Requesting unit<input name="requesting_unit" value="{{ old('requesting_unit', $purchaseRequest?->requesting_unit) }}" class="rounded-lg border border-slate-300 px-3 py-2"></label>
        <label class="flex flex-col gap-1 text-sm font-medium">Project reference<input name="project_reference" value="{{ old('project_reference', $purchaseRequest?->project_reference) }}" class="rounded-lg border border-slate-300 px-3 py-2"></label>
        <label class="flex flex-col gap-1 text-sm font-medium md:col-span-2">Purpose<textarea name="purpose" required rows="3" class="rounded-lg border border-slate-300 px-3 py-2">{{ old('purpose', $purchaseRequest?->purpose) }}</textarea>@error('purpose')<span class="text-red-700">{{ $message }}</span>@enderror</label>
    </div></section>
    <section class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div class="mb-4 flex items-center justify-between gap-4"><h2 class="font-semibold">Requested items and services</h2><button type="button" data-add-line class="rounded-lg border border-blue-300 px-3 py-2 text-sm font-semibold text-blue-700">Add line</button></div><div class="flex flex-col gap-4" data-lines>
        @foreach($formLines as $index => $line)<div class="grid gap-3 rounded-xl border border-slate-200 p-4 md:grid-cols-6" data-line>
            <label class="flex flex-col gap-1 text-sm font-medium md:col-span-2">Catalog item (optional)<select name="lines[{{ $index }}][product_service_id]" class="rounded-lg border border-slate-300 px-3 py-2"><option value="">Free-text item</option>@foreach($items as $item)<option value="{{ $item->id }}" @selected((string)($line['product_service_id'] ?? '') === (string)$item->id)>{{ $item->sku }} — {{ $item->name }} ({{ $item->type }})</option>@endforeach</select></label>
            <label class="flex flex-col gap-1 text-sm font-medium md:col-span-2">Description<input name="lines[{{ $index }}][description]" value="{{ $line['description'] ?? '' }}" required class="rounded-lg border border-slate-300 px-3 py-2"></label>
            <label class="flex flex-col gap-1 text-sm font-medium md:col-span-2">Preferred supplier<select name="lines[{{ $index }}][preferred_supplier_id]" class="rounded-lg border border-slate-300 px-3 py-2"><option value="">None</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}" @selected((string)($line['preferred_supplier_id'] ?? '') === (string)$supplier->id)>{{ $supplier->name }}</option>@endforeach</select></label>
            <label class="flex flex-col gap-1 text-sm font-medium">UOM code<input name="lines[{{ $index }}][uom_code]" value="{{ $line['uom_code'] ?? '' }}" class="rounded-lg border border-slate-300 px-3 py-2"></label>
            <label class="flex flex-col gap-1 text-sm font-medium">UOM name<input name="lines[{{ $index }}][uom_name]" value="{{ $line['uom_name'] ?? '' }}" class="rounded-lg border border-slate-300 px-3 py-2"></label>
            <label class="flex flex-col gap-1 text-sm font-medium">Quantity<input type="number" min="0.0001" step="0.0001" name="lines[{{ $index }}][quantity]" value="{{ $line['quantity'] ?? '1.0000' }}" required class="rounded-lg border border-slate-300 px-3 py-2"></label>
            <label class="flex flex-col gap-1 text-sm font-medium">Estimated unit cost<input type="number" min="0" step="0.0001" name="lines[{{ $index }}][estimated_unit_cost]" value="{{ $line['estimated_unit_cost'] ?? '0.0000' }}" required class="rounded-lg border border-slate-300 px-3 py-2"></label>
            <label class="flex flex-col gap-1 text-sm font-medium">Line notes<input name="lines[{{ $index }}][notes]" value="{{ $line['notes'] ?? '' }}" class="rounded-lg border border-slate-300 px-3 py-2"></label>
            <button type="button" data-remove-line class="self-end rounded-lg border border-red-300 px-3 py-2 text-sm font-semibold text-red-700">Remove</button>
        </div>@endforeach
    </div>@error('lines')<p class="mt-2 text-sm text-red-700">{{ $message }}</p>@enderror</section>
    <label class="flex flex-col gap-1 rounded-2xl bg-white p-6 text-sm font-medium shadow-sm ring-1 ring-slate-200">Notes<textarea name="notes" rows="3" class="rounded-lg border border-slate-300 px-3 py-2">{{ old('notes', $purchaseRequest?->notes) }}</textarea></label>
    <div class="flex gap-3"><button class="rounded-lg bg-blue-700 px-4 py-2 text-sm font-semibold text-white">{{ $submitLabel }}</button><a href="{{ route('purchase-requests.index') }}" class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold">Cancel</a></div>
    <template data-line-template><div class="grid gap-3 rounded-xl border border-slate-200 p-4 md:grid-cols-6" data-line><label class="flex flex-col gap-1 text-sm font-medium md:col-span-2">Catalog item (optional)<select name="lines[__INDEX__][product_service_id]" class="rounded-lg border border-slate-300 px-3 py-2"><option value="">Free-text item</option>@foreach($items as $item)<option value="{{ $item->id }}">{{ $item->sku }} — {{ $item->name }} ({{ $item->type }})</option>@endforeach</select></label><label class="flex flex-col gap-1 text-sm font-medium md:col-span-2">Description<input name="lines[__INDEX__][description]" required class="rounded-lg border border-slate-300 px-3 py-2"></label><label class="flex flex-col gap-1 text-sm font-medium md:col-span-2">Preferred supplier<select name="lines[__INDEX__][preferred_supplier_id]" class="rounded-lg border border-slate-300 px-3 py-2"><option value="">None</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}">{{ $supplier->name }}</option>@endforeach</select></label><label class="flex flex-col gap-1 text-sm font-medium">UOM code<input name="lines[__INDEX__][uom_code]" class="rounded-lg border border-slate-300 px-3 py-2"></label><label class="flex flex-col gap-1 text-sm font-medium">UOM name<input name="lines[__INDEX__][uom_name]" class="rounded-lg border border-slate-300 px-3 py-2"></label><label class="flex flex-col gap-1 text-sm font-medium">Quantity<input type="number" min="0.0001" step="0.0001" name="lines[__INDEX__][quantity]" value="1.0000" required class="rounded-lg border border-slate-300 px-3 py-2"></label><label class="flex flex-col gap-1 text-sm font-medium">Estimated unit cost<input type="number" min="0" step="0.0001" name="lines[__INDEX__][estimated_unit_cost]" value="0.0000" required class="rounded-lg border border-slate-300 px-3 py-2"></label><label class="flex flex-col gap-1 text-sm font-medium">Line notes<input name="lines[__INDEX__][notes]" class="rounded-lg border border-slate-300 px-3 py-2"></label><button type="button" data-remove-line class="self-end rounded-lg border border-red-300 px-3 py-2 text-sm font-semibold text-red-700">Remove</button></div></template>
</form>
