@props(['action', 'method' => 'POST', 'quotation' => null, 'customers', 'items', 'submitLabel'])
@php($formLines = old('lines', $quotation?->lines?->map(fn ($line) => ['product_service_id' => $line->product_service_id, 'description' => $line->description, 'quantity' => $line->quantity, 'unit_price' => $line->unit_price, 'discount_rate' => $line->discount_rate])->all() ?? [['product_service_id' => '', 'description' => '', 'quantity' => '1.0000', 'unit_price' => '0.0000', 'discount_rate' => '0.000000']]))
<form method="POST" action="{{ $action }}" class="flex flex-col gap-5" data-quotation-form>
    @csrf @if($method !== 'POST') @method($method) @endif
    <section class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div class="grid gap-4 md:grid-cols-2">
        <label class="flex flex-col gap-1 text-sm font-medium">Customer<select name="customer_id" required class="rounded-lg border border-slate-300 px-3 py-2"><option value="">Select customer</option>@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected((string)old('customer_id',$quotation?->customer_id)===(string)$customer->id)>{{ $customer->name }}</option>@endforeach</select>@error('customer_id')<span class="text-red-700">{{ $message }}</span>@enderror</label>
        <label class="flex flex-col gap-1 text-sm font-medium">Reference<input name="reference" value="{{ old('reference',$quotation?->reference) }}" class="rounded-lg border border-slate-300 px-3 py-2"></label>
        <label class="flex flex-col gap-1 text-sm font-medium">Quotation date<input type="date" name="quotation_date" value="{{ old('quotation_date',$quotation?->quotation_date?->toDateString() ?? now()->toDateString()) }}" required class="rounded-lg border border-slate-300 px-3 py-2">@error('quotation_date')<span class="text-red-700">{{ $message }}</span>@enderror</label>
        <label class="flex flex-col gap-1 text-sm font-medium">Valid until<input type="date" name="valid_until" value="{{ old('valid_until',$quotation?->valid_until?->toDateString() ?? now()->addDays(30)->toDateString()) }}" required class="rounded-lg border border-slate-300 px-3 py-2">@error('valid_until')<span class="text-red-700">{{ $message }}</span>@enderror</label>
        <label class="flex flex-col gap-1 text-sm font-medium">Contact name<input name="contact_name" value="{{ old('contact_name',$quotation?->contact_name) }}" class="rounded-lg border border-slate-300 px-3 py-2"></label>
        <label class="flex flex-col gap-1 text-sm font-medium">Contact email<input type="email" name="contact_email" value="{{ old('contact_email',$quotation?->contact_email) }}" class="rounded-lg border border-slate-300 px-3 py-2"></label>
        <label class="flex flex-col gap-1 text-sm font-medium">Contact phone<input name="contact_phone" value="{{ old('contact_phone',$quotation?->contact_phone) }}" class="rounded-lg border border-slate-300 px-3 py-2"></label>
        <label class="flex flex-col gap-1 text-sm font-medium">Document discount %<input type="number" min="0" max="100" step="0.000001" name="document_discount_rate" value="{{ old('document_discount_rate',$quotation?->document_discount_rate ?? '0.000000') }}" required class="rounded-lg border border-slate-300 px-3 py-2"></label>
        <label class="flex flex-col gap-1 text-sm font-medium md:col-span-2">Billing address<textarea name="billing_address" required rows="2" class="rounded-lg border border-slate-300 px-3 py-2">{{ old('billing_address',$quotation?->billing_address) }}</textarea>@error('billing_address')<span class="text-red-700">{{ $message }}</span>@enderror</label>
        <label class="flex flex-col gap-1 text-sm font-medium md:col-span-2">Delivery address<textarea name="delivery_address" required rows="2" class="rounded-lg border border-slate-300 px-3 py-2">{{ old('delivery_address',$quotation?->delivery_address) }}</textarea>@error('delivery_address')<span class="text-red-700">{{ $message }}</span>@enderror</label>
    </div></section>
    <section class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div class="mb-4 flex items-center justify-between gap-4"><h2 class="font-semibold">Quotation lines</h2><button type="button" data-add-line class="rounded-lg border border-blue-300 px-3 py-2 text-sm font-semibold text-blue-700">Add line</button></div>
        <div class="flex flex-col gap-4" data-lines>@foreach($formLines as $index => $line)<div class="grid gap-3 rounded-xl border border-slate-200 p-4 md:grid-cols-6" data-line>
            <label class="flex flex-col gap-1 text-sm font-medium md:col-span-2">Product/service<select name="lines[{{ $index }}][product_service_id]" required class="rounded-lg border border-slate-300 px-3 py-2"><option value="">Select item</option>@foreach($items as $item)<option value="{{ $item->id }}" @selected((string)($line['product_service_id']??'')===(string)$item->id)>{{ $item->sku }} — {{ $item->name }} ({{ ucfirst($item->type) }})</option>@endforeach</select></label>
            <label class="flex flex-col gap-1 text-sm font-medium md:col-span-4">Description<input name="lines[{{ $index }}][description]" value="{{ $line['description']??'' }}" required class="rounded-lg border border-slate-300 px-3 py-2"></label>
            <label class="flex flex-col gap-1 text-sm font-medium md:col-span-2">Quantity<input type="number" min="0.0001" step="0.0001" name="lines[{{ $index }}][quantity]" value="{{ $line['quantity']??'1.0000' }}" required class="rounded-lg border border-slate-300 px-3 py-2"></label>
            <label class="flex flex-col gap-1 text-sm font-medium md:col-span-2">Unit price<input type="number" min="0" step="0.0001" name="lines[{{ $index }}][unit_price]" value="{{ $line['unit_price']??'0.0000' }}" required class="rounded-lg border border-slate-300 px-3 py-2"></label>
            <label class="flex flex-col gap-1 text-sm font-medium">Discount %<input type="number" min="0" max="100" step="0.000001" name="lines[{{ $index }}][discount_rate]" value="{{ $line['discount_rate']??'0.000000' }}" required class="rounded-lg border border-slate-300 px-3 py-2"></label>
            <button type="button" data-remove-line class="self-end rounded-lg border border-red-300 px-3 py-2 text-sm font-semibold text-red-700">Remove</button>
        </div>@endforeach</div>
        @error('lines')<p class="mt-2 text-sm text-red-700">{{ $message }}</p>@enderror
    </section>
    <section class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div class="grid gap-4 md:grid-cols-2"><label class="flex flex-col gap-1 text-sm font-medium">Notes<textarea name="notes" rows="3" class="rounded-lg border border-slate-300 px-3 py-2">{{ old('notes',$quotation?->notes) }}</textarea></label><label class="flex flex-col gap-1 text-sm font-medium">Terms and conditions<textarea name="terms_and_conditions" rows="3" class="rounded-lg border border-slate-300 px-3 py-2">{{ old('terms_and_conditions',$quotation?->terms_and_conditions) }}</textarea></label></div></section>
    <div class="flex gap-3"><button class="rounded-lg bg-blue-700 px-4 py-2 text-sm font-semibold text-white">{{ $submitLabel }}</button><a href="{{ route('quotations.index') }}" class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold">Cancel</a></div>
    <template data-line-template><div class="grid gap-3 rounded-xl border border-slate-200 p-4 md:grid-cols-6" data-line><label class="flex flex-col gap-1 text-sm font-medium md:col-span-2">Product/service<select name="lines[__INDEX__][product_service_id]" required class="rounded-lg border border-slate-300 px-3 py-2"><option value="">Select item</option>@foreach($items as $item)<option value="{{ $item->id }}">{{ $item->sku }} — {{ $item->name }} ({{ ucfirst($item->type) }})</option>@endforeach</select></label><label class="flex flex-col gap-1 text-sm font-medium md:col-span-4">Description<input name="lines[__INDEX__][description]" required class="rounded-lg border border-slate-300 px-3 py-2"></label><label class="flex flex-col gap-1 text-sm font-medium md:col-span-2">Quantity<input type="number" min="0.0001" step="0.0001" name="lines[__INDEX__][quantity]" value="1.0000" required class="rounded-lg border border-slate-300 px-3 py-2"></label><label class="flex flex-col gap-1 text-sm font-medium md:col-span-2">Unit price<input type="number" min="0" step="0.0001" name="lines[__INDEX__][unit_price]" value="0.0000" required class="rounded-lg border border-slate-300 px-3 py-2"></label><label class="flex flex-col gap-1 text-sm font-medium">Discount %<input type="number" min="0" max="100" step="0.000001" name="lines[__INDEX__][discount_rate]" value="0.000000" required class="rounded-lg border border-slate-300 px-3 py-2"></label><button type="button" data-remove-line class="self-end rounded-lg border border-red-300 px-3 py-2 text-sm font-semibold text-red-700">Remove</button></div></template>
</form>
