@props(['filters', 'customers', 'action'])
<form method="GET" action="{{ $action }}" class="mb-5 grid gap-3 rounded-2xl bg-white p-5 ring-1 ring-slate-200 md:grid-cols-3 lg:grid-cols-6">
    <label class="grid gap-1 text-sm">As of<input type="date" name="as_of" value="{{ $filters['as_of'] }}" required class="rounded-lg border-slate-300"></label>
    <label class="grid gap-1 text-sm">Customer<select name="customer_id" class="rounded-lg border-slate-300"><option value="">All customers</option>@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected(($filters['customer_id'] ?? '') == $customer->id)>{{ $customer->name }}</option>@endforeach</select></label>
    <label class="grid gap-1 text-sm">Customer type<select name="customer_type" class="rounded-lg border-slate-300"><option value="">All types</option><option value="private" @selected(($filters['customer_type'] ?? '') === 'private')>Private</option><option value="government" @selected(($filters['customer_type'] ?? '') === 'government')>Government</option></select></label>
    <label class="grid gap-1 text-sm">Invoice state<select name="state" class="rounded-lg border-slate-300"><option value="">All open</option><option value="partial" @selected(($filters['state'] ?? '') === 'partial')>Partially paid</option><option value="overdue" @selected(($filters['state'] ?? '') === 'overdue')>Overdue</option></select></label>
    <label class="grid gap-1 text-sm">Aging bucket<select name="bucket" class="rounded-lg border-slate-300"><option value="">All buckets</option><option value="current" @selected(($filters['bucket'] ?? '') === 'current')>Current</option><option value="1-30" @selected(($filters['bucket'] ?? '') === '1-30')>1–30 days</option><option value="31-60" @selected(($filters['bucket'] ?? '') === '31-60')>31–60 days</option><option value="61-90" @selected(($filters['bucket'] ?? '') === '61-90')>61–90 days</option><option value="over-90" @selected(($filters['bucket'] ?? '') === 'over-90')>More than 90 days</option></select></label>
    <div class="flex items-end"><button class="w-full rounded-lg bg-blue-700 px-4 py-2 font-semibold text-white">Apply filters</button></div>
    @error('as_of')<p class="text-sm text-red-600 md:col-span-3 lg:col-span-6">{{ $message }}</p>@enderror
</form>
