<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><title>Tax Review Pack | {{ $period->label }}</title><style>body{font:14px Arial,sans-serif;color:#172033;max-width:1050px;margin:24px auto;padding:0 20px}h1,h2{margin:20px 0 8px}table{width:100%;border-collapse:collapse;margin:8px 0 18px}th,td{border:1px solid #ccd3dd;padding:7px;text-align:left}.notice{padding:12px;background:#eff6ff;border:1px solid #93c5fd}.issue{color:#991b1b}.sign{height:70px}@media print{.no-print{display:none}body{margin:0;max-width:none}}</style></head><body>
<button class="no-print" onclick="window.print()">Print</button><h1>Tax Compliance Review Pack</h1><p>{{ $period->label }} | {{ $period->capture_start->toDateString() }} to {{ $period->period_end->toDateString() }}</p><p class="notice">{{ $disclaimer }}</p>
<h2>Taxpayer and registration snapshot</h2><table>@foreach($taxpayer as $label=>$value)<tr><th>{{ str($label)->headline() }}</th><td>{{ $value ?? 'Not configured' }}</td></tr>@endforeach</table>
<h2>Tax-period summary</h2><table><tr><th>Form</th><th>Due date</th><th>Status</th><th>Filing</th><th>Payment</th></tr>@foreach($obligations as $obligation)<tr><td>{{ $obligation->bir_form_number }}</td><td>{{ $obligation->effectiveDueDate()->toDateString() }}</td><td>{{ str($obligation->status)->headline() }}</td><td>{{ str($obligation->filing_status)->headline() }}</td><td>{{ str($obligation->payment_status)->headline() }}</td></tr>@endforeach</table>
<h2>Sales and receipt reconciliation</h2><table><tr><th>Form</th><th>Gross sales</th><th>Receipts</th><th>Ledger revenue</th><th>Difference</th><th>Critical issues</th></tr>@foreach($obligations as $obligation)<tr><td>{{ $obligation->bir_form_number }}</td>@if($obligation->reconciliation)<td>{{ $obligation->reconciliation->gross_sales }}</td><td>{{ $obligation->reconciliation->receipt_basis }}</td><td>{{ $obligation->reconciliation->ledger_revenue }}</td><td>{{ $obligation->reconciliation->difference }}</td><td>{{ $obligation->reconciliation->critical_difference_count }}</td>@else<td colspan="5" class="issue">Missing reconciliation</td>@endif</tr>@endforeach</table>
@foreach($obligations as $obligation)@php($worksheet=$obligation->bir_form_number==='2551Q'?$obligation->bir2551qWorksheets->first():$obligation->bir1701qWorksheets->first())@if($worksheet)<h2>{{ $obligation->bir_form_number }} worksheet</h2><table><tr><th>Revision</th><th>Status</th><th>Taxable amount/income</th><th>Amount payable</th></tr><tr><td>{{ $worksheet->revision_number }}</td><td>{{ str($worksheet->status)->headline() }}</td><td>{{ $obligation->bir_form_number==='2551Q'?$worksheet->taxable_amount:$worksheet->taxable_income }}</td><td>{{ $worksheet->total_amount_payable }}</td></tr></table>@endif @endforeach
<h2>Withholding summary</h2><table><tr><th>Certificates/deductions</th><th>Verified amount</th><th>Missing certificate indicators</th></tr><tr><td>{{ $withholding['count'] }}</td><td>{{ $withholding['verified_amount'] }}</td><td>{{ $indicators['missing_certificates'] }}</td></tr></table>
<h2>Books and schedules index</h2><table>@foreach($schedule_index as $key=>$schedule)<tr><td>{{ $schedule['label'] }}</td><td>{{ str($schedule['group'])->headline() }}</td></tr>@endforeach</table>
<h2>Filing and payment history</h2><table><tr><th>Form</th><th>Return reference</th><th>Filed</th><th>Declared</th><th>Paid</th><th>Evidence files</th></tr>@foreach($obligations as $obligation)@forelse($obligation->taxFilings as $filing)<tr><td>{{ $filing->bir_form_number }}</td><td>{{ $filing->return_reference }}</td><td>{{ $filing->filing_date->toDateString() }}</td><td>{{ $filing->amount_declared }}</td><td>{{ $filing->amountPaid() }}</td><td>{{ $filing->attachments->count() }}</td></tr>@empty<tr><td>{{ $obligation->bir_form_number }}</td><td colspan="5" class="issue">No filing history</td></tr>@endforelse @endforeach</table>
<h2>Unresolved issues</h2><ul>@forelse($unresolved_issues as $issue=>$count)<li class="issue">{{ str($issue)->headline() }}: {{ $count }}</li>@empty<li>No automated unresolved indicators.</li>@endforelse @foreach($comments->where('status','open') as $comment)<li>{{ $comment->comment }} | {{ $comment->author->name }}</li>@endforeach</ul>
<h2>Preparer and reviewer sign-off</h2><table><tr><th>Prepared by / date</th><th>Reviewed by / date</th></tr><tr><td class="sign"></td><td class="sign"></td></tr></table><p>Generated {{ $generated_at->toDateTimeString() }}. Last refresh: {{ $last_refresh?->toDateTimeString() ?? 'Not generated' }}. Rule review: {{ $last_rule_review?->toDateString() ?? 'Not recorded' }}.</p>
</body></html>
