<x-app-layout title="Tax Compliance Dashboard">
    <div class="grid gap-6">
        <div class="flex flex-wrap items-end justify-between gap-4">
            <div><h1 class="text-2xl font-semibold text-slate-900">Tax compliance dashboard</h1><p class="text-sm text-slate-600">Period-specific preparation and review indicators. No filing or payment is performed here.</p></div>
            <nav aria-label="Tax periods" class="flex flex-wrap gap-2">@foreach($periods as $option)<a href="{{ route('tax-dashboard.show', $option) }}" class="rounded-lg px-3 py-2 text-sm {{ $option->id === $period->id ? 'bg-slate-800 text-white' : 'bg-white text-slate-700 ring-1 ring-slate-300' }}">{{ $option->label }}</a>@endforeach</nav>
        </div>
        <div class="flex flex-wrap gap-3 text-sm"><span>Period: <strong>{{ $period->label }}</strong></span><span>Last refresh: <strong>{{ $last_refresh?->toDateTimeString() ?? 'Not generated' }}</strong></span><span>Last rule review: <strong>{{ $last_rule_review?->toDateString() ?? 'Not recorded' }}</strong></span></div>
        <div class="rounded-xl bg-white p-4 text-sm ring-1 ring-slate-200"><strong>{{ $taxpayer['registered_name'] }}</strong><span class="ml-3">TIN {{ $taxpayer['tin'] }}</span><span class="ml-3">RDO {{ $taxpayer['rdo_code'] }}</span></div>
        @if($critical_blocker)<div class="rounded-xl border border-red-300 bg-red-50 p-4 font-medium text-red-900">Critical reconciliation issues remain. Ready-to-file indication is blocked until they are resolved.</div>@endif
        <div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">@foreach($indicators as $label => $count)<div class="rounded-xl bg-white p-4 ring-1 ring-slate-200"><div class="text-xs uppercase tracking-wide text-slate-500">{{ str($label)->headline() }}</div><div class="mt-1 text-2xl font-semibold {{ $count > 0 && in_array($label, ['overdue','missing_certificates','unreconciled_sales','failed_accounting_postings','missing_filing_or_payment_proof']) ? 'text-red-700' : 'text-slate-900' }}">{{ $count }}</div></div>@endforeach</div>
        <section class="rounded-2xl bg-white p-5 ring-1 ring-slate-200"><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="font-semibold">Review pack</h2><p class="text-sm text-slate-600">Taxpayer snapshot, applicable worksheets, schedules, filing evidence, unresolved issues, and sign-off.</p></div><div class="flex gap-2">@can('generate',$period)<a target="_blank" href="{{ route('tax-review-pack.print',$period) }}" class="rounded-lg border border-slate-300 px-3 py-2 text-sm">Printable pack</a>@endcan @can('download',$period)<a href="{{ route('tax-review-pack.download',$period) }}" class="rounded-lg bg-blue-700 px-3 py-2 text-sm text-white">Download HTML</a>@endcan</div></div></section>
        <section class="rounded-2xl bg-white p-5 ring-1 ring-slate-200"><h2 class="font-semibold">Review comments</h2><div class="mt-3 grid gap-3">@forelse($comments as $comment)<article class="rounded-lg bg-slate-50 p-3 text-sm"><div class="flex justify-between gap-3"><span>{{ $comment->comment }}</span><strong>{{ str($comment->status)->headline() }}</strong></div><div class="mt-1 text-xs text-slate-500">{{ $comment->author->name }} | {{ $comment->created_at->toDateTimeString() }}</div>@if($comment->status === 'open')@can('comment',$period)<form class="mt-2" method="POST" action="{{ route('tax-review-comments.store',$period) }}">@csrf<input type="hidden" name="status" value="resolved"><input type="hidden" name="comment_id" value="{{ $comment->id }}"><button class="text-blue-700 underline">Mark resolved</button></form>@endcan @endif</article>@empty<p class="text-sm text-slate-500">No review comments.</p>@endforelse</div>
            @can('comment',$period)<form method="POST" action="{{ route('tax-review-comments.store',$period) }}" class="mt-4 grid gap-2">@csrf<input type="hidden" name="status" value="open"><label class="grid gap-1 text-sm">New review comment<textarea name="comment" required class="rounded-lg border-slate-300"></textarea>@error('comment')<span class="text-red-700">{{ $message }}</span>@enderror</label><button class="justify-self-start rounded-lg bg-slate-800 px-3 py-2 text-sm text-white">Add comment</button></form>@endcan
        </section>
    </div>
</x-app-layout>
