<x-app-layout title="Withholding Reconciliation">
    <div class="flex flex-col gap-6">
        <div class="flex flex-wrap items-start justify-between gap-3"><div><h1 class="text-2xl font-semibold text-slate-900">Withholding certificates and tax credits</h1><p class="mt-1 text-sm text-slate-600">Review-only reconciliation of certificates, source transactions, return applications, and accounting control lines.</p></div>@can('withholding-reconciliation.export')<a href="{{ route('withholding-reconciliation.export', ['year' => $year]) }}" class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium">Export CSV</a>@endcan</div>
        <form class="flex gap-3 rounded-2xl bg-white p-4 ring-1 ring-slate-200"><label class="grid gap-1 text-sm">Tax year<input type="number" name="year" value="{{ $year }}" class="rounded-lg border-slate-300"></label><button class="self-end rounded-lg bg-slate-900 px-4 py-2 text-sm font-medium text-white">Refresh</button></form>
        <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">@foreach(['Verified certificates'=>'certificate_total','Matched control accounts'=>'ledger_total','Difference'=>'difference','Unapplied certificates'=>'unapplied_count'] as $label=>$field)<div class="rounded-2xl bg-white p-5 ring-1 ring-slate-200"><div class="text-xs font-medium uppercase tracking-wide text-slate-500">{{ $label }}</div><div class="mt-1 text-xl font-semibold">{{ $field === 'unapplied_count' ? $$field : '₱'.number_format((float)$$field, 4) }}</div></div>@endforeach</div>
        <section class="overflow-hidden rounded-2xl bg-white ring-1 ring-slate-200"><div class="border-b border-slate-200 p-5"><h2 class="font-semibold">Certificates and remaining credits</h2></div><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50"><tr><th class="px-4 py-3 text-left">Certificate</th><th class="px-4 py-3 text-left">Source</th><th class="px-4 py-3 text-right">Amount</th><th class="px-4 py-3 text-right">Applied</th><th class="px-4 py-3 text-right">Remaining</th><th class="px-4 py-3 text-left">Accounting</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($certificates as $certificate)<tr><td class="px-4 py-3"><a class="font-medium text-blue-700" href="{{ route('government-deductions.show', $certificate) }}">{{ $certificate->certificate_type }} {{ $certificate->certificate_number ?: 'Missing' }}</a><div class="text-xs text-slate-500">{{ str($certificate->status->value)->headline() }}</div></td><td class="px-4 py-3">{{ $certificate->customer->name }}<div class="text-xs text-slate-500">{{ $certificate->salesInvoice->invoice_number }}</div></td><td class="px-4 py-3 text-right">₱{{ number_format((float)$certificate->amount, 4) }}</td><td class="px-4 py-3 text-right">₱{{ number_format((float)$certificate->appliedAmount(), 4) }}</td><td class="px-4 py-3 text-right">₱{{ number_format((float)$certificate->remainingAmount(), 4) }}</td><td class="px-4 py-3">{{ $certificate->journalEntryLine ? 'Matched · ₱'.number_format((float)bcsub($certificate->journalEntryLine->debit, $certificate->journalEntryLine->credit, 4), 4) : 'Unmatched' }}</td></tr>@empty<tr><td colspan="6" class="px-4 py-8 text-center text-slate-500">No certificates for this year.</td></tr>@endforelse</tbody></table></div></section>
        <section class="overflow-hidden rounded-2xl bg-white ring-1 ring-slate-200"><div class="border-b border-slate-200 p-5"><h2 class="font-semibold">Missing certificates</h2></div><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><tbody class="divide-y divide-slate-100">@forelse($missing as $invoice)<tr><td class="px-4 py-3 font-medium">{{ $invoice->invoice_number }}</td><td class="px-4 py-3">{{ $invoice->customer->name }}</td><td class="px-4 py-3 text-right">Expected ₱{{ number_format((float)$invoice->expected_withholding_amount, 4) }}</td></tr>@empty<tr><td class="px-4 py-8 text-center text-slate-500" colspan="3">No missing certificates detected.</td></tr>@endforelse</tbody></table></div></section>
        <p class="text-xs text-slate-500">This reconciliation supports bookkeeping and tax-return preparation only. It does not file returns or validate legal entitlement to a credit.</p>
    </div>
</x-app-layout>
