<x-app-layout title="BIR 1701Q Worksheets">
    <div class="flex flex-col gap-6">
        <div><h1 class="text-2xl font-semibold text-slate-900">BIR Form 1701Q preparation</h1><p class="mt-1 text-sm text-slate-600">Cumulative quarterly income-tax review worksheets. These are not official returns or electronic submission files.</p></div>
        <div class="overflow-hidden rounded-2xl bg-white ring-1 ring-slate-200"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50"><tr><th class="px-4 py-3 text-left">Period</th><th class="px-4 py-3 text-left">Latest revision</th><th class="px-4 py-3 text-left">Status</th><th class="px-4 py-3 text-right">Action</th></tr></thead><tbody class="divide-y divide-slate-100">
            @forelse($obligations as $obligation) @php($latest = $obligation->bir1701qWorksheets->first())
                <tr><td class="px-4 py-3 font-medium">{{ $obligation->taxPeriod->label }}</td><td class="px-4 py-3">{{ $latest ? 'Revision '.$latest->revision_number.' · '.str($latest->return_type)->headline() : '—' }}</td><td class="px-4 py-3">{{ $latest ? str($latest->status)->headline() : 'Not prepared' }}</td><td class="px-4 py-3 text-right">@if($latest)<a class="rounded-lg border border-slate-300 px-3 py-2 font-medium" href="{{ route('bir-1701q.show', $latest) }}">View</a>@can('bir-1701q.prepare') @if($latest->frozen_at)<form method="POST" action="{{ route('bir-1701q.revise', $latest) }}" class="mt-2 flex justify-end gap-2">@csrf<input type="hidden" name="return_type" value="amended"><input required name="revision_reason" placeholder="Revision reason" class="rounded-lg border-slate-300 text-sm"><button class="rounded-lg bg-slate-900 px-3 py-2 font-medium text-white">Revise</button></form>@endif @endcan @else @can('bir-1701q.prepare')<form method="POST" action="{{ route('bir-1701q.store', $obligation) }}">@csrf<input type="hidden" name="return_type" value="original"><button class="rounded-lg bg-slate-900 px-3 py-2 font-medium text-white">Prepare</button></form>@endcan @endif</td></tr>
            @empty<tr><td colspan="4" class="px-4 py-10 text-center text-slate-500">No registered 1701Q obligations are available.</td></tr>@endforelse
        </tbody></table></div><div class="border-t border-slate-200 px-4 py-3">{{ $obligations->links() }}</div></div>
    </div>
</x-app-layout>
