<x-app-layout title="BIR 1701Q Worksheet">
    @php($money = fn ($value) => number_format((float) $value, 4))
    <div class="flex flex-col gap-6">
        <div class="flex flex-wrap items-start justify-between gap-3"><div><a href="{{ route('bir-1701q.index') }}" class="text-sm font-medium text-blue-700">← Back to 1701Q</a><h1 class="mt-2 text-2xl font-semibold text-slate-900">1701Q {{ $worksheet->taxable_year }} Q{{ $worksheet->quarter }}</h1><p class="text-sm text-slate-600">Revision {{ $worksheet->revision_number }} · {{ str($worksheet->return_type)->headline() }} · {{ str($worksheet->status)->headline() }}</p></div>@can('export', $worksheet)<a href="{{ route('bir-1701q.export', $worksheet) }}" class="rounded-lg border border-slate-300 px-3 py-2 text-sm font-medium">Export review CSV</a>@endcan</div>
        <div class="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">Preparation worksheet only. Review the configured tax method, supporting evidence, and BIR requirements before filing. This system does not file directly with BIR.</div>
        <section class="grid gap-4 rounded-2xl bg-white p-5 ring-1 ring-slate-200 sm:grid-cols-2 lg:grid-cols-4">
            @foreach(['Income-tax method' => $worksheet->income_tax_method, 'Deduction method' => $worksheet->deduction_method, 'Taxable income' => '₱'.$money($worksheet->taxable_income), 'Income tax due' => '₱'.$money($worksheet->income_tax_due), 'Verified CWT' => '₱'.$money($worksheet->verified_creditable_withholding), 'Prior payments' => '₱'.$money($worksheet->prior_quarter_payments), 'Penalties' => '₱'.$money($worksheet->surcharge + $worksheet->interest + $worksheet->compromise_penalty), 'Amount payable' => '₱'.$money($worksheet->total_amount_payable)] as $label => $value)<div><dt class="text-xs font-medium uppercase tracking-wide text-slate-500">{{ $label }}</dt><dd class="mt-1 font-semibold text-slate-900">{{ $value }}</dd></div>@endforeach
        </section>
        <section class="overflow-hidden rounded-2xl bg-white ring-1 ring-slate-200"><div class="border-b border-slate-200 p-5"><h2 class="font-semibold">Cumulative income statement basis</h2><a class="text-sm text-blue-700" href="{{ route('income-statement.index', $worksheet->financial_report_snapshot['parameters'] ?? []) }}">Open source financial report</a></div><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><tbody class="divide-y divide-slate-100">@foreach(['Cumulative gross sales'=>'cumulative_gross_sales','Returns and discounts'=>'sales_returns_discounts','Net sales'=>'net_sales','Cost of sales'=>'cost_of_sales','Other income'=>'other_income','Gross income'=>'gross_income','Financial itemized deductions'=>'financial_itemized_deductions','OSD deduction'=>'osd_deduction','Manual deduction adjustment'=>'manual_deduction_adjustment','Taxable-income adjustment'=>'taxable_income_adjustment'] as $label=>$field)<tr><th class="px-4 py-3 text-left font-medium">{{ $label }}</th><td class="px-4 py-3 text-right">₱{{ $money($worksheet->$field) }}</td></tr>@endforeach</tbody></table></div></section>
        @if($worksheet->status === 'draft') @can('update', $worksheet)<form method="POST" action="{{ route('bir-1701q.update', $worksheet) }}" class="grid gap-4 rounded-2xl bg-white p-5 ring-1 ring-slate-200 sm:grid-cols-2">@csrf @method('PATCH')<input type="hidden" name="return_type" value="{{ $worksheet->return_type }}">@foreach(['manual_deduction_adjustment'=>'Manual deduction adjustment','taxable_income_adjustment'=>'Taxable-income adjustment','prior_quarter_payments'=>'Prior-quarter payments','manual_creditable_withholding'=>'Manual CWT','other_allowable_credits'=>'Other credits','surcharge'=>'Surcharge','interest'=>'Interest','compromise_penalty'=>'Compromise penalty'] as $field=>$label)<label class="text-sm"><span class="font-medium">{{ $label }}</span><input name="{{ $field }}" value="{{ old($field, $worksheet->$field) }}" class="mt-1 w-full rounded-lg border-slate-300" inputmode="decimal">@error($field)<span class="text-red-600">{{ $message }}</span>@enderror</label>@endforeach @foreach(['manual_adjustment_reason'=>'Manual adjustment reason','manual_adjustment_evidence'=>'Manual adjustment evidence','prior_payment_evidence'=>'Prior-payment evidence','withholding_evidence'=>'Manual CWT evidence','other_credits_authority'=>'Other-credit authority','other_credits_evidence'=>'Other-credit evidence','penalty_authority'=>'Penalty authority','penalty_evidence'=>'Penalty evidence','preparation_notes'=>'Preparation notes'] as $field=>$label)<label class="text-sm"><span class="font-medium">{{ $label }}</span><input name="{{ $field }}" value="{{ old($field, $worksheet->$field) }}" class="mt-1 w-full rounded-lg border-slate-300">@error($field)<span class="text-red-600">{{ $message }}</span>@enderror</label>@endforeach<div class="sm:col-span-2 flex gap-2"><button class="rounded-lg border border-slate-300 px-4 py-2 font-medium">Recalculate</button></form><form method="POST" action="{{ route('bir-1701q.submit', $worksheet) }}">@csrf<button class="rounded-lg bg-slate-900 px-4 py-2 font-medium text-white">Submit for review</button></form></div>@endcan @endif
        <div class="flex flex-wrap gap-2">@if($worksheet->status === 'for_review') @can('review', $worksheet)<form method="POST" action="{{ route('bir-1701q.review', $worksheet) }}">@csrf<button class="rounded-lg bg-slate-900 px-4 py-2 text-white">Record review</button></form>@endcan @endif @if($worksheet->status === 'reviewed') @can('approve', $worksheet)<form method="POST" action="{{ route('bir-1701q.approve', $worksheet) }}">@csrf<label class="mr-2 text-sm"><input type="checkbox" name="confirm_freeze" value="1" required> Confirm worksheet freeze</label><button class="rounded-lg bg-emerald-700 px-4 py-2 text-white">Approve</button></form>@endcan @endif</div>
    </div>
</x-app-layout>
