<?php

use App\Http\Controllers\AccountController;
use App\Http\Controllers\AccountsPayableReportController;
use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\Auth\NewPasswordController;
use App\Http\Controllers\Auth\PasswordResetLinkController;
use App\Http\Controllers\BalanceSheetController;
use App\Http\Controllers\BankController;
use App\Http\Controllers\BankReconciliationController;
use App\Http\Controllers\BankStatementImportController;
use App\Http\Controllers\Bir1701qWorksheetController;
use App\Http\Controllers\Bir2551qWorksheetController;
use App\Http\Controllers\BooksAndSchedulesController;
use App\Http\Controllers\BrandController;
use App\Http\Controllers\BusinessProfileController;
use App\Http\Controllers\CanvassQuotationController;
use App\Http\Controllers\CashDisbursementController;
use App\Http\Controllers\CashFlowStatementController;
use App\Http\Controllers\CashPositionReportController;
use App\Http\Controllers\CashReceiptController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ComparativeReportController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\CustomerPaymentController;
use App\Http\Controllers\DeliveryController;
use App\Http\Controllers\DocumentSequenceController;
use App\Http\Controllers\ExpenseController;
use App\Http\Controllers\FinancialAccountController;
use App\Http\Controllers\FinancialDashboardController;
use App\Http\Controllers\FinancialReportPackController;
use App\Http\Controllers\FiscalPeriodController;
use App\Http\Controllers\FiscalYearController;
use App\Http\Controllers\FundTransferController;
use App\Http\Controllers\GeneralLedgerController;
use App\Http\Controllers\GovernmentDeductionController;
use App\Http\Controllers\IncomeStatementController;
use App\Http\Controllers\InventoryAdjustmentController;
use App\Http\Controllers\InventoryOpeningBalanceController;
use App\Http\Controllers\InventoryReportController;
use App\Http\Controllers\InventoryTransferController;
use App\Http\Controllers\JournalEntryController;
use App\Http\Controllers\ManagementReportController;
use App\Http\Controllers\OwnerEquityStatementController;
use App\Http\Controllers\PaymentMethodController;
use App\Http\Controllers\PettyCashController;
use App\Http\Controllers\PhysicalCountController;
use App\Http\Controllers\PostingRuleController;
use App\Http\Controllers\ProductServiceController;
use App\Http\Controllers\PurchaseOrderController;
use App\Http\Controllers\PurchaseRequestController;
use App\Http\Controllers\PurchasingAttachmentController;
use App\Http\Controllers\QuotationController;
use App\Http\Controllers\ReceivableReportController;
use App\Http\Controllers\ReceivingRecordController;
use App\Http\Controllers\RoleMatrixController;
use App\Http\Controllers\SalesAttachmentController;
use App\Http\Controllers\SalesInvoiceController;
use App\Http\Controllers\SalesOrderController;
use App\Http\Controllers\SourcePostingController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\SupplierInvoiceController;
use App\Http\Controllers\SupplierPaymentController;
use App\Http\Controllers\SystemSettingController;
use App\Http\Controllers\TaxCalendarController;
use App\Http\Controllers\TaxComplianceRuleController;
use App\Http\Controllers\TaxDashboardController;
use App\Http\Controllers\TaxFilingController;
use App\Http\Controllers\TaxProfileController;
use App\Http\Controllers\TaxReconciliationController;
use App\Http\Controllers\TrialBalanceController;
use App\Http\Controllers\UnitOfMeasureController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WarehouseController;
use App\Http\Controllers\WithholdingCertificateReconciliationController;
use App\Http\Middleware\EnsureUserIsActive;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Route::middleware('guest')->group(function () {
    Route::get('/login', [AuthenticatedSessionController::class, 'create'])->name('login');
    Route::post('/login', [AuthenticatedSessionController::class, 'store'])
        ->middleware('throttle:5,1')
        ->name('login.store');
    Route::get('/forgot-password', [PasswordResetLinkController::class, 'create'])->name('password.request');
    Route::post('/forgot-password', [PasswordResetLinkController::class, 'store'])->middleware('throttle:5,1')->name('password.email');
    Route::get('/reset-password/{token}', [NewPasswordController::class, 'create'])->name('password.reset');
    Route::post('/reset-password', [NewPasswordController::class, 'store'])->name('password.update');
});

Route::middleware(['auth', EnsureUserIsActive::class])->group(function () {
    Route::view('/dashboard', 'dashboard-home')->name('dashboard');
    Route::get('/tax-dashboard', [TaxDashboardController::class, 'index'])->name('tax-dashboard.index');
    Route::get('/tax-dashboard/{tax_period}', [TaxDashboardController::class, 'show'])->name('tax-dashboard.show');
    Route::get('/tax-review-pack/{tax_period}/print', [TaxDashboardController::class, 'print'])->name('tax-review-pack.print');
    Route::get('/tax-review-pack/{tax_period}/download', [TaxDashboardController::class, 'download'])->name('tax-review-pack.download');
    Route::post('/tax-periods/{tax_period}/review-comments', [TaxDashboardController::class, 'storeComment'])->name('tax-review-comments.store');
    Route::get('/financial-dashboard', FinancialDashboardController::class)->name('financial-dashboard');
    Route::get('/financial-report-pack', [FinancialReportPackController::class, 'show'])->name('financial-report-pack.show');
    Route::get('/financial-report-pack/download', [FinancialReportPackController::class, 'download'])->name('financial-report-pack.download');
    Route::get('/business-profile', [BusinessProfileController::class, 'edit'])->name('business-profile.edit');
    Route::put('/business-profile', [BusinessProfileController::class, 'update'])->name('business-profile.update');
    Route::get('/tax-profile', [TaxProfileController::class, 'edit'])->name('tax-profile.edit');
    Route::put('/tax-profile', [TaxProfileController::class, 'update'])->name('tax-profile.update');
    Route::post('/tax-profile/rates', [TaxProfileController::class, 'storeRate'])->name('tax-profile.rates.store');
    Route::patch('/tax-rules/{tax_compliance_rule}/activate', [TaxComplianceRuleController::class, 'activate'])->name('tax-rules.activate');
    Route::patch('/tax-rules/{tax_compliance_rule}/deactivate', [TaxComplianceRuleController::class, 'deactivate'])->name('tax-rules.deactivate');
    Route::patch('/tax-rules/{tax_compliance_rule}/review', [TaxComplianceRuleController::class, 'review'])->name('tax-rules.review');
    Route::resource('tax-rules', TaxComplianceRuleController::class)
        ->parameters(['tax-rules' => 'tax_compliance_rule'])
        ->only(['index', 'store', 'edit', 'update']);
    Route::get('/tax-calendar', [TaxCalendarController::class, 'index'])->name('tax-calendar.index');
    Route::post('/tax-calendar/generate', [TaxCalendarController::class, 'generate'])->name('tax-calendar.generate');
    Route::patch('/tax-calendar/{tax_obligation}', [TaxCalendarController::class, 'update'])->name('tax-calendar.update');
    Route::post('/tax-calendar/{tax_obligation}/deadline-adjustments', [TaxCalendarController::class, 'adjustDeadline'])->name('tax-calendar.deadline-adjustments.store');
    Route::get('/tax-reconciliations', [TaxReconciliationController::class, 'index'])->name('tax-reconciliations.index');
    Route::get('/books-of-accounts', [BooksAndSchedulesController::class, 'index'])->name('books-of-accounts.index');
    Route::get('/books-of-accounts/print', [BooksAndSchedulesController::class, 'print'])->name('books-of-accounts.print');
    Route::get('/books-of-accounts/export', [BooksAndSchedulesController::class, 'export'])->name('books-of-accounts.export');
    Route::get('/tax-schedules', [BooksAndSchedulesController::class, 'index'])->name('tax-schedules.index');
    Route::get('/tax-schedules/print', [BooksAndSchedulesController::class, 'print'])->name('tax-schedules.print');
    Route::get('/tax-schedules/export', [BooksAndSchedulesController::class, 'export'])->name('tax-schedules.export');
    Route::post('/tax-reconciliations/obligations/{tax_obligation}', [TaxReconciliationController::class, 'generate'])->name('tax-reconciliations.generate');
    Route::get('/tax-reconciliations/{tax_reconciliation}', [TaxReconciliationController::class, 'show'])->name('tax-reconciliations.show');
    Route::get('/tax-reconciliations/{tax_reconciliation}/export', [TaxReconciliationController::class, 'export'])->name('tax-reconciliations.export');
    Route::post('/tax-reconciliations/{tax_reconciliation}/adjustments', [TaxReconciliationController::class, 'storeAdjustment'])->name('tax-reconciliations.adjustments.store');
    Route::patch('/tax-reconciliation-adjustments/{tax_reconciliation_adjustment}', [TaxReconciliationController::class, 'reviewAdjustment'])->name('tax-reconciliations.adjustments.review');
    Route::get('/bir-2551q', [Bir2551qWorksheetController::class, 'index'])->name('bir-2551q.index');
    Route::post('/bir-2551q/obligations/{tax_obligation}', [Bir2551qWorksheetController::class, 'store'])->name('bir-2551q.store');
    Route::get('/bir-2551q/{bir_2551q_worksheet}', [Bir2551qWorksheetController::class, 'show'])->name('bir-2551q.show');
    Route::patch('/bir-2551q/{bir_2551q_worksheet}', [Bir2551qWorksheetController::class, 'update'])->name('bir-2551q.update');
    Route::post('/bir-2551q/{bir_2551q_worksheet}/submit', [Bir2551qWorksheetController::class, 'submit'])->name('bir-2551q.submit');
    Route::post('/bir-2551q/{bir_2551q_worksheet}/review', [Bir2551qWorksheetController::class, 'review'])->name('bir-2551q.review');
    Route::post('/bir-2551q/{bir_2551q_worksheet}/approve', [Bir2551qWorksheetController::class, 'approve'])->name('bir-2551q.approve');
    Route::post('/bir-2551q/{bir_2551q_worksheet}/revise', [Bir2551qWorksheetController::class, 'revise'])->name('bir-2551q.revise');
    Route::get('/bir-2551q/{bir_2551q_worksheet}/export', [Bir2551qWorksheetController::class, 'export'])->name('bir-2551q.export');
    Route::get('/bir-1701q', [Bir1701qWorksheetController::class, 'index'])->name('bir-1701q.index');
    Route::post('/bir-1701q/obligations/{tax_obligation}', [Bir1701qWorksheetController::class, 'store'])->name('bir-1701q.store');
    Route::get('/bir-1701q/{bir_1701q_worksheet}', [Bir1701qWorksheetController::class, 'show'])->name('bir-1701q.show');
    Route::patch('/bir-1701q/{bir_1701q_worksheet}', [Bir1701qWorksheetController::class, 'update'])->name('bir-1701q.update');
    Route::post('/bir-1701q/{bir_1701q_worksheet}/submit', [Bir1701qWorksheetController::class, 'submit'])->name('bir-1701q.submit');
    Route::post('/bir-1701q/{bir_1701q_worksheet}/review', [Bir1701qWorksheetController::class, 'review'])->name('bir-1701q.review');
    Route::post('/bir-1701q/{bir_1701q_worksheet}/approve', [Bir1701qWorksheetController::class, 'approve'])->name('bir-1701q.approve');
    Route::post('/bir-1701q/{bir_1701q_worksheet}/revise', [Bir1701qWorksheetController::class, 'revise'])->name('bir-1701q.revise');
    Route::get('/bir-1701q/{bir_1701q_worksheet}/export', [Bir1701qWorksheetController::class, 'export'])->name('bir-1701q.export');
    Route::get('/fiscal-years', [FiscalYearController::class, 'index'])->name('fiscal-years.index');
    Route::post('/fiscal-years', [FiscalYearController::class, 'store'])->name('fiscal-years.store');
    Route::get('/fiscal-periods/{fiscalPeriod}', [FiscalPeriodController::class, 'show'])->name('fiscal-periods.show');
    Route::get('/fiscal-periods/{fiscalPeriod}/preclose', [FiscalPeriodController::class, 'preclose'])->name('fiscal-periods.preclose');
    Route::patch('/fiscal-periods/{fiscalPeriod}/status', [FiscalPeriodController::class, 'update'])->name('fiscal-periods.status.update');
    Route::get('/document-sequences', [DocumentSequenceController::class, 'index'])->name('document-sequences.index');
    Route::post('/document-sequences', [DocumentSequenceController::class, 'store'])->name('document-sequences.store');
    Route::put('/document-sequences/{documentSequence}', [DocumentSequenceController::class, 'update'])->name('document-sequences.update');
    Route::post('/document-sequences/{documentSequence}/issue', [DocumentSequenceController::class, 'issue'])->name('document-sequences.issue');
    Route::resource('users', UserController::class)->except(['show', 'destroy']);
    Route::get('/roles', RoleMatrixController::class)->name('roles.index');
    Route::get('/system-settings', [SystemSettingController::class, 'edit'])->name('system-settings.edit');
    Route::put('/system-settings', [SystemSettingController::class, 'update'])->name('system-settings.update');
    Route::resource('customers', CustomerController::class)->except('show');
    Route::resource('suppliers', SupplierController::class)->except('show');
    Route::resource('units-of-measure', UnitOfMeasureController::class)
        ->parameters(['units-of-measure' => 'unit_of_measure'])
        ->except('show');
    Route::resource('categories', CategoryController::class)->except('show');
    Route::patch('/accounts/{account}/status', [AccountController::class, 'status'])->name('accounts.status');
    Route::resource('accounts', AccountController::class)->except(['show', 'destroy']);
    Route::patch('/journal-entries/{journal_entry}/status', [JournalEntryController::class, 'transition'])->name('journal-entries.transition');
    Route::post('/journal-entries/{journal_entry}/reverse', [JournalEntryController::class, 'reverse'])->name('journal-entries.reverse');
    Route::post('/journal-entries/{journal_entry}/correct', [JournalEntryController::class, 'correct'])->name('journal-entries.correct');
    Route::resource('journal-entries', JournalEntryController::class)->except('destroy');
    Route::get('/general-journal', [GeneralLedgerController::class, 'journal'])->name('general-journal.index');
    Route::get('/general-journal/print', [GeneralLedgerController::class, 'print'])->name('general-journal.print');
    Route::get('/general-journal/export', [GeneralLedgerController::class, 'export'])->name('general-journal.export');
    Route::get('/general-ledger', [GeneralLedgerController::class, 'ledger'])->name('general-ledger.index');
    Route::get('/general-ledger/print', [GeneralLedgerController::class, 'print'])->name('general-ledger.print');
    Route::get('/general-ledger/export', [GeneralLedgerController::class, 'export'])->name('general-ledger.export');
    Route::get('/account-activity', [GeneralLedgerController::class, 'activity'])->name('account-activity.index');
    Route::get('/account-activity/print', [GeneralLedgerController::class, 'print'])->name('account-activity.print');
    Route::get('/account-activity/export', [GeneralLedgerController::class, 'export'])->name('account-activity.export');
    Route::get('/trial-balance', [TrialBalanceController::class, 'index'])->name('trial-balance.index');
    Route::get('/trial-balance/print', [TrialBalanceController::class, 'print'])->name('trial-balance.print');
    Route::get('/trial-balance/export', [TrialBalanceController::class, 'export'])->name('trial-balance.export');
    Route::get('/subledger-reconciliations', [TrialBalanceController::class, 'reconciliations'])->name('subledger-reconciliations.index');
    Route::get('/subledger-reconciliations/print', [TrialBalanceController::class, 'print'])->name('subledger-reconciliations.print');
    Route::get('/subledger-reconciliations/export', [TrialBalanceController::class, 'export'])->name('subledger-reconciliations.export');
    Route::get('/income-statement', [IncomeStatementController::class, 'index'])->name('income-statement.index');
    Route::get('/income-statement/print', [IncomeStatementController::class, 'print'])->name('income-statement.print');
    Route::get('/income-statement/export', [IncomeStatementController::class, 'export'])->name('income-statement.export');
    Route::get('/income-statement/accounts/{account}', [IncomeStatementController::class, 'drilldown'])->name('income-statement.drilldown');
    Route::get('/balance-sheet', [BalanceSheetController::class, 'index'])->name('balance-sheet.index');
    Route::get('/balance-sheet/print', [BalanceSheetController::class, 'print'])->name('balance-sheet.print');
    Route::get('/balance-sheet/export', [BalanceSheetController::class, 'export'])->name('balance-sheet.export');
    Route::get('/balance-sheet/accounts/{account}', [BalanceSheetController::class, 'drilldown'])->name('balance-sheet.drilldown');
    Route::get('/cash-flow-statement', [CashFlowStatementController::class, 'index'])->name('cash-flow-statement.index');
    Route::get('/cash-flow-statement/print', [CashFlowStatementController::class, 'print'])->name('cash-flow-statement.print');
    Route::get('/cash-flow-statement/export', [CashFlowStatementController::class, 'export'])->name('cash-flow-statement.export');
    Route::get('/cash-flow-statement/mappings', [CashFlowStatementController::class, 'mappings'])->name('cash-flow-statement.mappings');
    Route::get('/cash-flow-statement/accounts/{account}', [CashFlowStatementController::class, 'drilldown'])->name('cash-flow-statement.drilldown');
    Route::get('/owner-equity-statement', [OwnerEquityStatementController::class, 'index'])->name('owner-equity-statement.index');
    Route::get('/owner-equity-statement/print', [OwnerEquityStatementController::class, 'print'])->name('owner-equity-statement.print');
    Route::get('/owner-equity-statement/export', [OwnerEquityStatementController::class, 'export'])->name('owner-equity-statement.export');
    Route::get('/owner-equity-statement/activities/{activity}', [OwnerEquityStatementController::class, 'drilldown'])->name('owner-equity-statement.drilldown');
    Route::get('/comparative-reports', [ComparativeReportController::class, 'index'])->name('comparative-reports.index');
    Route::get('/comparative-reports/print', [ComparativeReportController::class, 'print'])->name('comparative-reports.print');
    Route::get('/comparative-reports/export', [ComparativeReportController::class, 'export'])->name('comparative-reports.export');
    Route::get('/management-reports', [ManagementReportController::class, 'index'])->name('management-reports.index');
    Route::get('/management-reports/print', [ManagementReportController::class, 'print'])->name('management-reports.print');
    Route::get('/management-reports/export', [ManagementReportController::class, 'export'])->name('management-reports.export');
    Route::post('/posting-rules/preview', [PostingRuleController::class, 'preview'])->name('posting-rules.preview');
    Route::patch('/posting-rules/{posting_rule}/status', [PostingRuleController::class, 'status'])->name('posting-rules.status');
    Route::resource('posting-rules', PostingRuleController::class)->except(['show', 'destroy']);
    Route::get('/source-postings', [SourcePostingController::class, 'index'])->name('source-postings.index');
    Route::post('/source-postings/{source_posting}/retry', [SourcePostingController::class, 'retry'])->name('source-postings.retry');
    Route::post('/source-postings/{source_posting}/rebuild-link', [SourcePostingController::class, 'rebuildLink'])->name('source-postings.rebuild-link');
    Route::resource('products-services', ProductServiceController::class)
        ->parameters(['products-services' => 'product_service'])
        ->except('show');
    Route::resource('brands', BrandController::class)->except('show');
    Route::resource('warehouses', WarehouseController::class)->except('show');
    Route::resource('payment-methods', PaymentMethodController::class)
        ->parameters(['payment-methods' => 'payment_method'])
        ->except('show');
    Route::resource('banks', BankController::class)->except('show');
    Route::patch('/financial-accounts/{financial_account}/status', [FinancialAccountController::class, 'status'])->name('financial-accounts.status');
    Route::resource('financial-accounts', FinancialAccountController::class)->except('destroy');
    Route::patch('/cash-receipts/{cash_receipt}/status', [CashReceiptController::class, 'transition'])->name('cash-receipts.transition');
    Route::get('/cash-receipts/{cash_receipt}/print', [CashReceiptController::class, 'print'])->name('cash-receipts.print');
    Route::resource('cash-receipts', CashReceiptController::class)->except('destroy');
    Route::patch('/cash-disbursements/{cash_disbursement}/status', [CashDisbursementController::class, 'transition'])->name('cash-disbursements.transition');
    Route::get('/cash-disbursements/{cash_disbursement}/print', [CashDisbursementController::class, 'print'])->name('cash-disbursements.print');
    Route::resource('cash-disbursements', CashDisbursementController::class)->except('destroy');
    Route::patch('/fund-transfers/{fund_transfer}/status', [FundTransferController::class, 'transition'])->name('fund-transfers.transition');
    Route::resource('fund-transfers', FundTransferController::class)->only(['index', 'create', 'store', 'show']);
    Route::get('/petty-cash', [PettyCashController::class, 'index'])->name('petty-cash.index');
    Route::get('/petty-cash/funds/create', [PettyCashController::class, 'createFund'])->name('petty-cash.funds.create');
    Route::post('/petty-cash/funds', [PettyCashController::class, 'storeFund'])->name('petty-cash.funds.store');
    Route::get('/petty-cash/funds/{petty_cash_fund}', [PettyCashController::class, 'showFund'])->name('petty-cash.funds.show');
    Route::put('/petty-cash/funds/{petty_cash_fund}', [PettyCashController::class, 'updateFund'])->name('petty-cash.funds.update');
    Route::get('/petty-cash/vouchers/create', [PettyCashController::class, 'createVoucher'])->name('petty-cash.vouchers.create');
    Route::post('/petty-cash/vouchers', [PettyCashController::class, 'storeVoucher'])->name('petty-cash.vouchers.store');
    Route::get('/petty-cash/vouchers/{petty_cash_voucher}', [PettyCashController::class, 'showVoucher'])->name('petty-cash.vouchers.show');
    Route::patch('/petty-cash/vouchers/{petty_cash_voucher}/status', [PettyCashController::class, 'transition'])->name('petty-cash.vouchers.transition');
    Route::post('/petty-cash/replenishments', [PettyCashController::class, 'replenish'])->name('petty-cash.replenishments.store');
    Route::get('/bank-statements/{bank_statement}/export', [BankStatementImportController::class, 'export'])->name('bank-statements.export');
    Route::resource('bank-statements', BankStatementImportController::class)->only(['index', 'create', 'store', 'show', 'destroy']);
    Route::post('/bank-reconciliations/{bank_reconciliation}/matches', [BankReconciliationController::class, 'match'])->name('bank-reconciliations.matches.store');
    Route::post('/bank-reconciliations/{bank_reconciliation}/adjustments', [BankReconciliationController::class, 'adjustment'])->name('bank-reconciliations.adjustments.store');
    Route::patch('/bank-reconciliations/{bank_reconciliation}/status', [BankReconciliationController::class, 'transition'])->name('bank-reconciliations.transition');
    Route::resource('bank-reconciliations', BankReconciliationController::class)->only(['index', 'create', 'store', 'show']);
    Route::get('/cash-reports', [CashPositionReportController::class, 'index'])->name('cash-reports.index');
    Route::get('/cash-reports/print', [CashPositionReportController::class, 'print'])->name('cash-reports.print');
    Route::get('/cash-reports/export', [CashPositionReportController::class, 'export'])->name('cash-reports.export');
    Route::get('/inventory-reports', [InventoryReportController::class, 'index'])->name('inventory-reports.index');
    Route::get('/inventory-reports/print', [InventoryReportController::class, 'print'])->name('inventory-reports.print');
    Route::get('/inventory-reports/export', [InventoryReportController::class, 'export'])->name('inventory-reports.export');
    Route::patch('/inventory-opening-balances/{inventory_opening_balance}/status', [InventoryOpeningBalanceController::class, 'transition'])->name('inventory-opening-balances.transition');
    Route::resource('inventory-opening-balances', InventoryOpeningBalanceController::class)->only(['index', 'create', 'store', 'show']);
    Route::patch('/inventory-adjustments/{inventory_adjustment}/status', [InventoryAdjustmentController::class, 'transition'])->name('inventory-adjustments.transition');
    Route::resource('inventory-adjustments', InventoryAdjustmentController::class)->only(['index', 'create', 'store', 'show']);
    Route::patch('/inventory-transfers/{inventory_transfer}/status', [InventoryTransferController::class, 'transition'])->name('inventory-transfers.transition');
    Route::resource('inventory-transfers', InventoryTransferController::class)->only(['index', 'create', 'store', 'show']);
    Route::put('/physical-counts/{physical_count}/counts', [PhysicalCountController::class, 'record'])->name('physical-counts.record');
    Route::patch('/physical-counts/{physical_count}/review', [PhysicalCountController::class, 'review'])->name('physical-counts.review');
    Route::patch('/physical-counts/{physical_count}/status', [PhysicalCountController::class, 'transition'])->name('physical-counts.transition');
    Route::resource('physical-counts', PhysicalCountController::class)->only(['index', 'create', 'store', 'show']);
    Route::patch('/purchase-requests/{purchase_request}/status', [PurchaseRequestController::class, 'transition'])->name('purchase-requests.transition');
    Route::resource('purchase-requests', PurchaseRequestController::class);
    Route::post('/purchase-requests/{purchase_request}/canvass-quotations', [CanvassQuotationController::class, 'store'])->name('purchase-requests.canvass-quotations.store');
    Route::put('/purchase-requests/{purchase_request}/canvass-quotations/{canvass_quotation}', [CanvassQuotationController::class, 'update'])->name('purchase-requests.canvass-quotations.update');
    Route::delete('/purchase-requests/{purchase_request}/canvass-quotations/{canvass_quotation}', [CanvassQuotationController::class, 'destroy'])->name('purchase-requests.canvass-quotations.destroy');
    Route::post('/purchase-requests/{purchase_request}/convert-to-order', [PurchaseOrderController::class, 'convert'])->name('purchase-requests.convert-to-order');
    Route::patch('/purchase-orders/{purchase_order}/status', [PurchaseOrderController::class, 'transition'])->name('purchase-orders.transition');
    Route::get('/purchase-orders/{purchase_order}/print', [PurchaseOrderController::class, 'print'])->name('purchase-orders.print');
    Route::resource('purchase-orders', PurchaseOrderController::class);
    Route::get('/purchase-orders/{purchase_order}/receiving-records/create', [ReceivingRecordController::class, 'create'])->name('receiving-records.create');
    Route::patch('/receiving-records/{receiving_record}/status', [ReceivingRecordController::class, 'transition'])->name('receiving-records.transition');
    Route::get('/receiving-records/{receiving_record}/print', [ReceivingRecordController::class, 'print'])->name('receiving-records.print');
    Route::resource('receiving-records', ReceivingRecordController::class)->only(['index', 'store', 'show', 'destroy']);
    Route::patch('/supplier-invoices/{supplier_invoice}/status', [SupplierInvoiceController::class, 'transition'])->name('supplier-invoices.transition');
    Route::get('/supplier-invoices/{supplier_invoice}/print', [SupplierInvoiceController::class, 'print'])->name('supplier-invoices.print');
    Route::resource('supplier-invoices', SupplierInvoiceController::class);
    Route::patch('/supplier-payments/{supplier_payment}/status', [SupplierPaymentController::class, 'transition'])->name('supplier-payments.transition');
    Route::post('/supplier-payments/{supplier_payment}/allocations', [SupplierPaymentController::class, 'allocate'])->name('supplier-payments.allocate');
    Route::get('/supplier-payments/{supplier_payment}/print', [SupplierPaymentController::class, 'print'])->name('supplier-payments.print');
    Route::resource('supplier-payments', SupplierPaymentController::class);
    Route::patch('/expenses/{expense}/status', [ExpenseController::class, 'transition'])->name('expenses.transition');
    Route::get('/expenses/{expense}/print', [ExpenseController::class, 'print'])->name('expenses.print');
    Route::resource('expenses', ExpenseController::class);
    Route::patch('/quotations/{quotation}/status', [QuotationController::class, 'transition'])->name('quotations.transition');
    Route::get('/quotations/{quotation}/print', [QuotationController::class, 'print'])->name('quotations.print');
    Route::resource('quotations', QuotationController::class);
    Route::post('/quotations/{quotation}/convert', [SalesOrderController::class, 'convert'])->name('quotations.convert');
    Route::patch('/sales-orders/{sales_order}/status', [SalesOrderController::class, 'transition'])->name('sales-orders.transition');
    Route::patch('/sales-orders/{sales_order}/fulfillment', [SalesOrderController::class, 'fulfill'])->name('sales-orders.fulfill');
    Route::resource('sales-orders', SalesOrderController::class);
    Route::patch('/deliveries/{delivery}/status', [DeliveryController::class, 'transition'])->name('deliveries.transition');
    Route::get('/deliveries/{delivery}/print', [DeliveryController::class, 'print'])->name('deliveries.print');
    Route::resource('deliveries', DeliveryController::class)->only(['index', 'create', 'store', 'show']);
    Route::patch('/sales-invoices/{sales_invoice}/status', [SalesInvoiceController::class, 'transition'])->name('sales-invoices.transition');
    Route::get('/sales-invoices/{sales_invoice}/print', [SalesInvoiceController::class, 'print'])->name('sales-invoices.print');
    Route::resource('sales-invoices', SalesInvoiceController::class)->except('destroy');
    Route::patch('/customer-payments/{customer_payment}/status', [CustomerPaymentController::class, 'transition'])->name('customer-payments.transition');
    Route::post('/customer-payments/{customer_payment}/allocations', [CustomerPaymentController::class, 'allocate'])->name('customer-payments.allocate');
    Route::resource('customer-payments', CustomerPaymentController::class)->except('destroy');
    Route::get('/receivables', [ReceivableReportController::class, 'index'])->name('receivables.index');
    Route::get('/receivables/summary', [ReceivableReportController::class, 'summary'])->name('receivables.summary');
    Route::get('/receivables/unapplied', [ReceivableReportController::class, 'unapplied'])->name('receivables.unapplied');
    Route::get('/receivables/print', [ReceivableReportController::class, 'print'])->name('receivables.print');
    Route::get('/receivables/export', [ReceivableReportController::class, 'export'])->name('receivables.export');
    Route::get('/customers/{customer}/statement', [ReceivableReportController::class, 'statement'])->name('customer-statements.show');
    Route::get('/customers/{customer}/statement/print', [ReceivableReportController::class, 'statementPrint'])->name('customer-statements.print');
    Route::get('/payables', [AccountsPayableReportController::class, 'index'])->name('payables.index');
    Route::get('/payables/summary', [AccountsPayableReportController::class, 'summary'])->name('payables.summary');
    Route::get('/payables/unapplied', [AccountsPayableReportController::class, 'unapplied'])->name('payables.unapplied');
    Route::get('/payables/expenses', [AccountsPayableReportController::class, 'expenses'])->name('payables.expenses');
    Route::get('/payables/print', [AccountsPayableReportController::class, 'print'])->name('payables.print');
    Route::get('/payables/export', [AccountsPayableReportController::class, 'export'])->name('payables.export');
    Route::get('/suppliers/{supplier}/statement', [AccountsPayableReportController::class, 'statement'])->name('supplier-statements.show');
    Route::get('/suppliers/{supplier}/statement/print', [AccountsPayableReportController::class, 'statementPrint'])->name('supplier-statements.print');
    Route::patch('/government-deductions/{government_deduction}/status', [GovernmentDeductionController::class, 'transition'])->name('government-deductions.transition');
    Route::get('/withholding-reconciliation', [WithholdingCertificateReconciliationController::class, 'index'])->name('withholding-reconciliation.index');
    Route::get('/tax-filings', [TaxFilingController::class, 'index'])->name('tax-filings.index');
    Route::post('/tax-filings', [TaxFilingController::class, 'store'])->name('tax-filings.store');
    Route::get('/tax-filings/{tax_filing}', [TaxFilingController::class, 'show'])->name('tax-filings.show');
    Route::post('/tax-filings/{tax_filing}/payments', [TaxFilingController::class, 'storePayment'])->name('tax-filings.payments.store');
    Route::post('/tax-filings/{tax_filing}/attachments', [TaxFilingController::class, 'storeAttachment'])->name('tax-filings.attachments.store');
    Route::get('/tax-filing-attachments/{tax_filing_attachment}/download', [TaxFilingController::class, 'download'])->name('tax-filing-attachments.download');
    Route::get('/withholding-reconciliation/export', [WithholdingCertificateReconciliationController::class, 'export'])->name('withholding-reconciliation.export');
    Route::post('/government-deductions/{government_deduction}/applications', [WithholdingCertificateReconciliationController::class, 'apply'])->name('government-deductions.applications.store');
    Route::resource('government-deductions', GovernmentDeductionController::class)->except('destroy');
    Route::post('/sales-attachments/{attachableType}/{attachableId}', [SalesAttachmentController::class, 'store'])->whereNumber('attachableId')->name('sales-attachments.store');
    Route::get('/sales-attachments/{salesAttachment}/download', [SalesAttachmentController::class, 'download'])->name('sales-attachments.download');
    Route::delete('/sales-attachments/{salesAttachment}', [SalesAttachmentController::class, 'destroy'])->name('sales-attachments.destroy');
    Route::post('/purchasing-attachments/{attachableType}/{attachableId}', [PurchasingAttachmentController::class, 'store'])->whereNumber('attachableId')->name('purchasing-attachments.store');
    Route::get('/purchasing-attachments/{purchasingAttachment}/download', [PurchasingAttachmentController::class, 'download'])->name('purchasing-attachments.download');
    Route::delete('/purchasing-attachments/{purchasingAttachment}', [PurchasingAttachmentController::class, 'destroy'])->name('purchasing-attachments.destroy');
    Route::post('/logout', [AuthenticatedSessionController::class, 'destroy'])->name('logout');
});
