<?php

use App\Actions\SaveJournalEntry;
use App\Actions\TransitionJournalEntry;
use App\Enums\JournalEntryStatus;
use App\Models\Account;
use App\Models\BusinessProfile;
use App\Models\Customer;
use App\Models\FiscalPeriod;
use App\Models\FiscalYear;
use App\Models\JournalEntry;
use App\Models\JournalEntryLine;
use App\Models\SalesInvoice;
use App\Models\User;
use Carbon\CarbonImmutable;
use Database\Seeders\ChartOfAccountsSeeder;
use Database\Seeders\RolesAndPermissionsSeeder;
use Illuminate\Foundation\Testing\LazilyRefreshDatabase;

uses(LazilyRefreshDatabase::class);

function financialOutputContext(): array
{
    test()->seed([RolesAndPermissionsSeeder::class, ChartOfAccountsSeeder::class]);
    $user = User::factory()->create(['name' => 'Report Operator']);
    $user->assignRole('Bookkeeper');
    BusinessProfile::factory()->active()->create(['registered_business_name' => 'Omni ICT Supplies']);
    $year = FiscalYear::factory()->create(['name' => 'FY 2026', 'starts_on' => '2026-01-01', 'ends_on' => '2026-12-31', 'is_current' => true]);
    $period = FiscalPeriod::factory()->create([
        'fiscal_year_id' => $year->id, 'name' => 'July 2026', 'starts_on' => '2026-07-01', 'ends_on' => '2026-07-31',
        'calendar_year' => 2026, 'calendar_month' => 7, 'calendar_quarter' => 3, 'status' => 'open',
    ]);
    $accounts = Account::query()->whereIn('code', ['1010', '4010'])->get()->keyBy('code');
    $invoice = SalesInvoice::factory()->create([
        'customer_id' => Customer::factory()->create()->id, 'fiscal_period_id' => $period->id,
        'invoice_number' => 'SI-OUTPUT-001', 'invoice_date' => '2026-07-15', 'due_date' => '2026-08-15', 'status' => 'posted',
    ]);
    $entry = app(SaveJournalEntry::class)->handle([
        'journal_number' => 'OUT-001', 'journal_date' => '2026-07-15', 'document_date' => '2026-07-15',
        'fiscal_period_id' => $period->id, 'journal_type' => 'sales', 'source_type' => 'sales_invoice',
        'source_id' => $invoice->id, 'reference_number' => 'SI-OUTPUT-001', 'description' => 'Output test',
        'lines' => [
            ['account_id' => $accounts['1010']->id, 'debit' => '100.0000', 'credit' => '0.0000'],
            ['account_id' => $accounts['4010']->id, 'debit' => '0.0000', 'credit' => '100.0000'],
        ],
    ], $user->id);
    $entry = app(TransitionJournalEntry::class)->handle($entry, JournalEntryStatus::Posted, $user->id);

    return compact('user', 'period', 'accounts', 'invoice', 'entry');
}

function financialOutputFilters(): array
{
    return [
        'start_date' => '2026-07-01', 'end_date' => '2026-07-31', 'as_of' => '2026-07-31',
        'fiscal_period_id' => null, 'report_view' => 'period', 'show_zero_balances' => false,
    ];
}

it('prints required metadata and configured confidential label', function (): void {
    $context = financialOutputContext();
    CarbonImmutable::setTestNow('2026-08-01 06:00:00');
    config(['financial_reports.confidential_label' => 'Confidential — Internal Use Only']);

    $this->actingAs($context['user'])->get(route('income-statement.print', financialOutputFilters()))
        ->assertSuccessful()
        ->assertSee('Omni ICT Supplies')
        ->assertSee('Income Statement')
        ->assertSee('2026-07-01 to 2026-07-31')
        ->assertSee('Accrual basis')
        ->assertSee('Generated 2026-08-01 06:00:00 PST by Report Operator')
        ->assertSee('Confidential — Internal Use Only');
});

it('exports matching totals metadata and timestamped filename without mutating data', function (): void {
    $context = financialOutputContext();
    CarbonImmutable::setTestNow('2026-08-01 06:00:00');
    $before = [JournalEntry::query()->count(), JournalEntryLine::query()->count(), $context['entry']->fresh()->updated_at->toISOString()];

    $response = $this->actingAs($context['user'])->get(route('income-statement.export', financialOutputFilters()))
        ->assertSuccessful()
        ->assertDownload('income-statement-2026-07-31-20260801-060000.csv');
    $csv = $response->streamedContent();

    expect($csv)->toContain('"Business Name","Omni ICT Supplies"')
        ->toContain('"Report Name","Income Statement"')
        ->toContain('"Generated By","Report Operator"')
        ->toContain('"Revenue Total",,,100.0000')
        ->and([JournalEntry::query()->count(), JournalEntryLine::query()->count(), $context['entry']->fresh()->updated_at->toISOString()])
        ->toBe($before);
});

it('preserves drilldown filters and protects journal and source links', function (): void {
    $context = financialOutputContext();
    $filters = financialOutputFilters();
    $route = route('income-statement.drilldown', ['account' => $context['accounts']['4010'], ...$filters]);

    $this->actingAs($context['user'])->get($route)
        ->assertSuccessful()
        ->assertSee(route('income-statement.index', $filters))
        ->assertSee(route('journal-entries.show', $context['entry']), false)
        ->assertSee(route('sales-invoices.show', $context['invoice']), false)
        ->assertSee('SI-OUTPUT-001')
        ->assertDontSee('#'.$context['invoice']->id);

    $restricted = User::factory()->create();
    $restricted->givePermissionTo(['income-statement.view', 'income-statement.drilldown', 'financial-reports.drilldown', 'journals.view']);
    $this->actingAs($restricted)->get($route)
        ->assertSuccessful()
        ->assertSee(route('journal-entries.show', $context['entry']), false)
        ->assertDontSee(route('sales-invoices.show', $context['invoice']), false);
});

it('enforces generic output permissions and paginates large drilldowns', function (): void {
    $context = financialOutputContext();
    $viewer = User::factory()->create();
    $viewer->assignRole('Viewer');
    $this->actingAs($viewer)->get(route('income-statement.print', financialOutputFilters()))->assertForbidden();
    $this->actingAs($viewer)->get(route('income-statement.export', financialOutputFilters()))->assertForbidden();

    $now = now();
    for ($sequence = 2; $sequence <= 56; $sequence++) {
        $entryId = JournalEntry::query()->insertGetId([
            'journal_number' => 'OUT-'.str_pad((string) $sequence, 3, '0', STR_PAD_LEFT),
            'journal_date' => '2026-07-15', 'document_date' => '2026-07-15', 'fiscal_period_id' => $context['period']->id,
            'journal_type' => 'adjustment', 'source_type' => 'manual', 'description' => 'Large drilldown',
            'total_debit' => '1.0000', 'total_credit' => '1.0000', 'status' => 'posted', 'posted_at' => $now,
            'posted_by' => $context['user']->id, 'created_by' => $context['user']->id, 'updated_by' => $context['user']->id,
            'created_at' => $now, 'updated_at' => $now,
        ]);
        JournalEntryLine::query()->insert([
            ['journal_entry_id' => $entryId, 'account_id' => $context['accounts']['1010']->id, 'line_number' => 1, 'debit' => '1.0000', 'credit' => '0.0000', 'created_at' => $now, 'updated_at' => $now],
            ['journal_entry_id' => $entryId, 'account_id' => $context['accounts']['4010']->id, 'line_number' => 2, 'debit' => '0.0000', 'credit' => '1.0000', 'created_at' => $now, 'updated_at' => $now],
        ]);
    }

    $this->actingAs($context['user'])->get(route('income-statement.drilldown', [
        'account' => $context['accounts']['4010'], ...financialOutputFilters(), 'page' => 2,
    ]))->assertSuccessful()->assertSee('OUT-056');
});
