<x-app-layout title="BIR 2551Q Worksheet">
    @php($allSources = array_merge(data_get($worksheet->source_snapshot, 'included', []), data_get($worksheet->source_snapshot, 'excluded', [])))
    <div class="flex flex-col gap-6">
        <div class="flex flex-wrap items-start justify-between gap-4"><div><h1 class="text-2xl font-semibold text-slate-900">2551Q — {{ $worksheet->return_year }} Q{{ $worksheet->quarter }}</h1><p class="mt-1 text-sm text-slate-600">Revision {{ $worksheet->revision_number }} · {{ str($worksheet->return_type)->headline() }} · {{ str($worksheet->status)->headline() }}</p></div><div class="flex gap-2"><a class="rounded-lg border border-slate-300 px-3 py-2 text-sm font-medium" href="{{ route('bir-2551q.index') }}">Back</a>@can('export', $worksheet)<a class="rounded-lg bg-slate-900 px-3 py-2 text-sm font-medium text-white" href="{{ route('bir-2551q.export', $worksheet) }}">Export review CSV</a>@endcan</div></div>

        <div class="rounded-2xl bg-amber-50 p-4 text-sm text-amber-900 ring-1 ring-amber-200"><strong>Preparation worksheet only.</strong> Figures must be reviewed and encoded or filed through the appropriate BIR channel. This system does not directly file or pay the return.</div>

        <section class="rounded-2xl bg-white p-5 ring-1 ring-slate-200"><h2 class="font-semibold">Taxpayer and rule snapshot</h2><dl class="mt-4 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><dt class="text-slate-500">Registered name</dt><dd class="font-medium">{{ data_get($worksheet->taxpayer_snapshot, 'registered_business_name') }}</dd></div><div><dt class="text-slate-500">TIN / branch</dt><dd class="font-medium">{{ data_get($worksheet->taxpayer_snapshot, 'tin') }} / {{ data_get($worksheet->taxpayer_snapshot, 'branch_code') }}</dd></div><div><dt class="text-slate-500">Tax-base rule</dt><dd class="font-medium">{{ data_get($worksheet->rule_snapshot, 'tax_base_rule') }}</dd></div><div><dt class="text-slate-500">Resolved rate</dt><dd class="font-medium">{{ $worksheet->tax_rate }}%</dd></div></dl></section>

        <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach(['Gross taxable amount' => 'gross_taxable_amount', 'Excluded / exempt' => 'excluded_amount', 'Taxable amount' => 'taxable_amount', 'Gross tax due' => 'gross_tax_due', 'Allowable credits' => 'allowable_credits', 'Government tax withheld' => 'government_tax_withheld', 'Prior payment' => 'prior_payment', 'Total amount payable' => 'total_amount_payable'] as $label => $field)<div class="rounded-2xl bg-white p-4 ring-1 ring-slate-200"><p class="text-xs font-semibold uppercase tracking-wide text-slate-500">{{ $label }}</p><p class="mt-2 text-xl font-semibold">PHP {{ number_format((float) $worksheet->{$field}, 4) }}</p></div>@endforeach</div>

        <section class="overflow-hidden rounded-2xl bg-white ring-1 ring-slate-200"><div class="flex flex-wrap items-center justify-between gap-3 p-5"><h2 class="font-semibold">Included and excluded sources</h2><a class="text-sm font-medium text-blue-700" href="{{ route('tax-reconciliations.show', $worksheet->tax_reconciliation_id) }}">Open source reconciliation</a></div><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50"><tr><th class="px-4 py-3 text-left">Treatment</th><th class="px-4 py-3 text-left">Type</th><th class="px-4 py-3 text-left">Reference</th><th class="px-4 py-3 text-left">Date</th><th class="px-4 py-3 text-right">Amount</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach($allSources as $source) @php($excluded = in_array($source['key'], $worksheet->excluded_source_keys ?? [], true))<tr><td class="px-4 py-3">{{ $excluded ? 'Excluded' : 'Included' }}</td><td class="px-4 py-3">{{ str($source['type'])->headline() }}</td><td class="px-4 py-3">@if($source['type'] === 'sales_invoice')<a class="font-medium text-blue-700" href="{{ route('sales-invoices.show', str($source['key'])->after(':')) }}">{{ $source['reference'] }}</a>@elseif($source['type'] === 'collection')<a class="font-medium text-blue-700" href="{{ route('customer-payments.show', str($source['key'])->after(':')) }}">{{ $source['reference'] }}</a>@else{{ $source['reference'] }}@endif</td><td class="px-4 py-3">{{ $source['date'] }}</td><td class="px-4 py-3 text-right">{{ number_format((float) $source['amount'], 4) }}</td></tr>@endforeach</tbody></table></div></section>

        @if($worksheet->status === 'draft') @can('update', $worksheet)
            <section class="rounded-2xl bg-white p-5 ring-1 ring-slate-200"><h2 class="font-semibold">Worksheet inputs</h2><form method="POST" action="{{ route('bir-2551q.update', $worksheet) }}" class="mt-4 grid gap-4 md:grid-cols-2">@csrf @method('PATCH')<input type="hidden" name="basis_type" value="{{ $worksheet->basis_type }}"><input type="hidden" name="return_type" value="{{ $worksheet->return_type }}">
                <fieldset class="md:col-span-2"><legend class="text-sm font-medium">Excluded sources</legend><div class="mt-2 grid gap-2 sm:grid-cols-2">@foreach($allSources as $source)<label class="flex items-center gap-2 rounded-lg bg-slate-50 p-3 text-sm"><input type="checkbox" name="excluded_source_keys[]" value="{{ $source['key'] }}" @checked(in_array($source['key'], old('excluded_source_keys', $worksheet->excluded_source_keys ?? []), true))>{{ $source['reference'] }} — PHP {{ number_format((float) $source['amount'], 4) }}</label>@endforeach</div></fieldset>
                @foreach(['exclusion_reason' => 'Exclusion reason', 'exclusion_evidence' => 'Exclusion evidence', 'credits_authority' => 'Credits authority', 'credits_evidence' => 'Credits evidence', 'prior_payment_reference' => 'Prior payment reference', 'penalty_authority' => 'Penalty authority', 'penalty_evidence' => 'Penalty evidence'] as $field => $label)<div><label class="text-sm font-medium">{{ $label }}</label><input name="{{ $field }}" value="{{ old($field, $worksheet->{$field}) }}" class="mt-1 w-full rounded-lg border-slate-300">@error($field)<p class="text-sm text-red-600">{{ $message }}</p>@enderror</div>@endforeach
                @foreach(['allowable_credits' => 'Allowable credits', 'prior_payment' => 'Prior payment / overpayment', 'surcharge' => 'Surcharge', 'interest' => 'Interest', 'compromise_penalty' => 'Compromise penalty'] as $field => $label)<div><label class="text-sm font-medium">{{ $label }}</label><input name="{{ $field }}" value="{{ old($field, $worksheet->{$field}) }}" class="mt-1 w-full rounded-lg border-slate-300">@error($field)<p class="text-sm text-red-600">{{ $message }}</p>@enderror</div>@endforeach
                <div class="md:col-span-2"><label class="text-sm font-medium">Preparation notes</label><textarea name="preparation_notes" class="mt-1 w-full rounded-lg border-slate-300">{{ old('preparation_notes', $worksheet->preparation_notes) }}</textarea></div><div class="md:col-span-2 flex gap-2"><button class="rounded-lg bg-slate-900 px-4 py-2 text-sm font-medium text-white">Recalculate and save</button></div>
            </form><form method="POST" action="{{ route('bir-2551q.submit', $worksheet) }}" class="mt-3">@csrf<button class="rounded-lg bg-blue-700 px-4 py-2 text-sm font-medium text-white">Submit for review</button></form></section>
        @endcan @endif

        <div class="flex flex-wrap gap-3">@if($worksheet->status === 'for_review')@can('review', $worksheet)<form method="POST" action="{{ route('bir-2551q.review', $worksheet) }}">@csrf<button class="rounded-lg bg-blue-700 px-4 py-2 text-sm font-medium text-white">Mark reviewed</button></form>@endcan @endif @if($worksheet->status === 'reviewed')@can('approve', $worksheet)<form method="POST" action="{{ route('bir-2551q.approve', $worksheet) }}" class="flex items-center gap-3 rounded-xl bg-emerald-50 p-3 ring-1 ring-emerald-200">@csrf<label class="flex items-center gap-2 text-sm"><input type="checkbox" name="confirm_freeze" value="1" required>I confirm this revision will be frozen.</label><button class="rounded-lg bg-emerald-700 px-4 py-2 text-sm font-medium text-white">Approve ready to file</button></form>@endcan @endif</div>

        @if($worksheet->frozen_at) @can('revise', $worksheet)<section class="rounded-2xl bg-white p-5 ring-1 ring-slate-200"><h2 class="font-semibold">Create a new revision</h2><form method="POST" action="{{ route('bir-2551q.revise', $worksheet) }}" class="mt-4 grid gap-3 md:grid-cols-3">@csrf<input type="hidden" name="basis_type" value="{{ $worksheet->basis_type }}">@foreach($worksheet->excluded_source_keys ?? [] as $key)<input type="hidden" name="excluded_source_keys[]" value="{{ $key }}">@endforeach @foreach(['allowable_credits', 'prior_payment', 'surcharge', 'interest', 'compromise_penalty', 'exclusion_reason', 'exclusion_evidence', 'credits_authority', 'credits_evidence', 'prior_payment_reference', 'penalty_authority', 'penalty_evidence', 'preparation_notes'] as $field)<input type="hidden" name="{{ $field }}" value="{{ $worksheet->{$field} }}">@endforeach<div><label class="text-sm font-medium">Return type</label><select name="return_type" class="mt-1 w-full rounded-lg border-slate-300"><option value="original">Original revision</option><option value="amended">Amended return</option></select></div><div class="md:col-span-2"><label class="text-sm font-medium">Revision reason</label><input name="revision_reason" required class="mt-1 w-full rounded-lg border-slate-300"></div><div class="md:col-span-3"><button class="rounded-lg bg-slate-900 px-4 py-2 text-sm font-medium text-white">Create revision</button></div></form></section>@endcan @endif
    </div>
</x-app-layout>
