<x-app-layout title="System Settings">
    <x-page-header title="System Settings" description="Maintain controlled application-wide defaults and operational labels." />
    <div class="mb-5 rounded-lg border border-blue-200 bg-blue-50 px-4 py-3 text-sm text-blue-900">Credentials, API keys, SMTP secrets, database settings, and backup execution are intentionally excluded.</div>
    <form method="POST" action="{{ route('system-settings.update') }}" class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200">
        @csrf @method('PUT')
        <div class="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
            <label class="flex flex-col gap-1 text-sm font-medium">Application display name<input name="settings[application_display_name]" value="{{ old('settings.application_display_name', $settings['application_display_name']) }}" required class="rounded-lg border border-slate-300 px-3 py-2">@error('settings.application_display_name')<span class="text-red-700">{{ $message }}</span>@enderror</label>
            <label class="flex flex-col gap-1 text-sm font-medium">Default date format<select name="settings[default_date_format]" class="rounded-lg border border-slate-300 px-3 py-2">@foreach (['Y-m-d','m/d/Y','d/m/Y','M j Y'] as $format)<option value="{{ $format }}" @selected(old('settings.default_date_format', $settings['default_date_format']) === $format)>{{ $format }}</option>@endforeach</select></label>
            <label class="flex flex-col gap-1 text-sm font-medium">Default time format<select name="settings[default_time_format]" class="rounded-lg border border-slate-300 px-3 py-2">@foreach (['H:i','h:i A'] as $format)<option value="{{ $format }}" @selected(old('settings.default_time_format', $settings['default_time_format']) === $format)>{{ $format }}</option>@endforeach</select></label>
            <label class="flex flex-col gap-1 text-sm font-medium">Default currency<input name="settings[default_currency]" value="{{ old('settings.default_currency', $settings['default_currency']) }}" maxlength="3" required class="rounded-lg border border-slate-300 px-3 py-2"></label>
            <label class="flex flex-col gap-1 text-sm font-medium">Currency symbol<input name="settings[currency_symbol]" value="{{ old('settings.currency_symbol', $settings['currency_symbol']) }}" required class="rounded-lg border border-slate-300 px-3 py-2"></label>
            <label class="flex flex-col gap-1 text-sm font-medium">Monetary decimal places<input type="number" min="0" max="4" name="settings[decimal_places]" value="{{ old('settings.decimal_places', $settings['decimal_places']) }}" required class="rounded-lg border border-slate-300 px-3 py-2"></label>
            <label class="flex flex-col gap-1 text-sm font-medium">Quantity decimal places<input type="number" min="0" max="4" name="settings[quantity_decimal_places]" value="{{ old('settings.quantity_decimal_places', $settings['quantity_decimal_places']) }}" required class="rounded-lg border border-slate-300 px-3 py-2"></label>
            <label class="flex flex-col gap-1 text-sm font-medium">Default paper size<select name="settings[default_paper_size]" class="rounded-lg border border-slate-300 px-3 py-2">@foreach (['A4','Letter','Legal'] as $size)<option value="{{ $size }}" @selected(old('settings.default_paper_size', $settings['default_paper_size']) === $size)>{{ $size }}</option>@endforeach</select></label>
            <label class="flex flex-col gap-1 text-sm font-medium">Records per page<input type="number" min="10" max="100" name="settings[records_per_page]" value="{{ old('settings.records_per_page', $settings['records_per_page']) }}" required class="rounded-lg border border-slate-300 px-3 py-2"></label>
            <label class="flex flex-col gap-1 text-sm font-medium">Low-stock default threshold<input name="settings[low_stock_default_threshold]" value="{{ old('settings.low_stock_default_threshold', $settings['low_stock_default_threshold']) }}" required class="rounded-lg border border-slate-300 px-3 py-2"></label>
            <label class="flex flex-col gap-1 text-sm font-medium">Attachment maximum size (KB)<input type="number" min="1" max="51200" name="settings[attachment_max_size]" value="{{ old('settings.attachment_max_size', $settings['attachment_max_size']) }}" required class="rounded-lg border border-slate-300 px-3 py-2"></label>
            <label class="flex flex-col gap-1 text-sm font-medium">Backup path label<input name="settings[backup_path_label]" value="{{ old('settings.backup_path_label', $settings['backup_path_label']) }}" required class="rounded-lg border border-slate-300 px-3 py-2"><span class="text-xs font-normal text-slate-500">Display label only; this does not configure or run backups.</span></label>
            <label class="flex flex-col gap-1 text-sm font-medium">Maintenance contact name<input name="settings[maintenance_contact_name]" value="{{ old('settings.maintenance_contact_name', $settings['maintenance_contact_name']) }}" class="rounded-lg border border-slate-300 px-3 py-2"></label>
            <label class="flex flex-col gap-1 text-sm font-medium">Maintenance contact email<input type="email" name="settings[maintenance_contact_email]" value="{{ old('settings.maintenance_contact_email', $settings['maintenance_contact_email']) }}" class="rounded-lg border border-slate-300 px-3 py-2">@error('settings.maintenance_contact_email')<span class="text-red-700">{{ $message }}</span>@enderror</label>
        </div>
        @error('settings')<p class="mt-3 text-sm text-red-700">{{ $message }}</p>@enderror
        <button class="mt-5 rounded-lg bg-blue-700 px-4 py-2 text-sm font-semibold text-white">Save system settings</button>
    </form>
</x-app-layout>
