@php($editing = isset($customerPayment))
<x-app-layout :title="$editing ? 'Edit Customer Payment' : 'Record Customer Payment'">
    <x-page-header :title="$editing ? 'Edit Customer Payment' : 'Record Customer Payment'" description="Keep cash, withholding, and other deductions separate." />
    <form method="POST" action="{{ $editing ? route('customer-payments.update', $customerPayment) : route('customer-payments.store') }}" class="grid gap-5 rounded-2xl bg-white p-6 ring-1 ring-slate-200 md:grid-cols-2">
        @csrf @if($editing) @method('PUT') @endif
        <label class="grid gap-1 text-sm">Customer<select name="customer_id" required class="rounded-lg border-slate-300"><option value="">Select customer</option>@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected(old('customer_id', $customerPayment->customer_id ?? '') == $customer->id)>{{ $customer->name }}</option>@endforeach</select>@error('customer_id')<span class="text-red-600">{{ $message }}</span>@enderror</label>
        <label class="grid gap-1 text-sm">Payment method<select name="payment_method_id" required class="rounded-lg border-slate-300"><option value="">Select method</option>@foreach($paymentMethods as $method)<option value="{{ $method->id }}" @selected(old('payment_method_id', $customerPayment->payment_method_id ?? '') == $method->id)>{{ $method->name }}</option>@endforeach</select>@error('payment_method_id')<span class="text-red-600">{{ $message }}</span>@enderror</label>
        <label class="grid gap-1 text-sm">Bank (optional)<select name="bank_id" class="rounded-lg border-slate-300"><option value="">None</option>@foreach($banks as $bank)<option value="{{ $bank->id }}" @selected(old('bank_id', $customerPayment->bank_id ?? '') == $bank->id)>{{ $bank->name }}</option>@endforeach</select>@error('bank_id')<span class="text-red-600">{{ $message }}</span>@enderror</label>
        <label class="grid gap-1 text-sm">Payment date<input type="date" name="payment_date" value="{{ old('payment_date', isset($customerPayment) ? $customerPayment->payment_date->toDateString() : now()->toDateString()) }}" required class="rounded-lg border-slate-300">@error('payment_date')<span class="text-red-600">{{ $message }}</span>@enderror</label>
        <label class="grid gap-1 text-sm">Reference number<input name="reference_number" value="{{ old('reference_number', $customerPayment->reference_number ?? '') }}" class="rounded-lg border-slate-300">@error('reference_number')<span class="text-red-600">{{ $message }}</span>@enderror</label>
        <div></div>
        @foreach(['gross_settlement_amount' => 'Gross settlement', 'withholding_amount' => 'Withholding', 'other_deductions' => 'Other deductions', 'net_cash_received' => 'Net cash received'] as $field => $label)<label class="grid gap-1 text-sm">{{ $label }}<input type="number" name="{{ $field }}" step="0.0001" min="0" value="{{ old($field, $customerPayment->{$field} ?? '0.0000') }}" required class="rounded-lg border-slate-300">@error($field)<span class="text-red-600">{{ $message }}</span>@enderror</label>@endforeach
        <label class="grid gap-1 text-sm md:col-span-2">Notes<textarea name="notes" rows="3" class="rounded-lg border-slate-300">{{ old('notes', $customerPayment->notes ?? '') }}</textarea>@error('notes')<span class="text-red-600">{{ $message }}</span>@enderror</label>
        <div class="md:col-span-2"><button class="rounded-lg bg-blue-700 px-4 py-2 font-semibold text-white">Save draft</button></div>
    </form>
</x-app-layout>
