<x-app-layout title="Customer Payment">
    <x-page-header title="{{ $customerPayment->payment_number ?? 'Draft #'.$customerPayment->id }}" description="{{ ucfirst(str_replace('_', ' ', $customerPayment->status->value)) }} payment from {{ $customerPayment->customer->name }}" />
    <div class="grid gap-5 lg:grid-cols-3">
        <section class="rounded-2xl bg-white p-6 ring-1 ring-slate-200 lg:col-span-2"><dl class="grid grid-cols-2 gap-3 text-sm"><dt>Date</dt><dd>{{ $customerPayment->payment_date->format('M d, Y') }}</dd><dt>Method</dt><dd>{{ $customerPayment->paymentMethod->name }}</dd><dt>Bank</dt><dd>{{ $customerPayment->bank?->name ?? '—' }}</dd><dt>Reference</dt><dd>{{ $customerPayment->reference_number ?? '—' }}</dd></dl></section>
        <section class="rounded-2xl bg-white p-6 ring-1 ring-slate-200"><dl class="grid grid-cols-2 gap-3 text-sm"><dt>Gross settlement</dt><dd class="text-right">₱{{ number_format((float) $customerPayment->gross_settlement_amount, 2) }}</dd><dt>Withholding</dt><dd class="text-right">₱{{ number_format((float) $customerPayment->withholding_amount, 2) }}</dd><dt>Other deductions</dt><dd class="text-right">₱{{ number_format((float) $customerPayment->other_deductions, 2) }}</dd><dt>Net cash</dt><dd class="text-right">₱{{ number_format((float) $customerPayment->net_cash_received, 2) }}</dd><dt class="font-bold">Unapplied</dt><dd class="text-right font-bold">₱{{ number_format((float) $customerPayment->unapplied_amount, 2) }}</dd></dl></section>
    </div>
    <section class="mt-5 rounded-2xl bg-white p-6 ring-1 ring-slate-200"><h2 class="font-semibold">Allocations</h2><div class="mt-3 overflow-x-auto"><table class="min-w-full text-sm"><thead><tr><th class="text-left">Invoice</th><th class="text-right">Amount</th><th>Status</th></tr></thead><tbody>@forelse($customerPayment->allocations as $allocation)<tr class="border-t"><td class="py-3">{{ $allocation->salesInvoice->invoice_number }}</td><td class="text-right">₱{{ number_format((float) $allocation->amount, 2) }}</td><td class="text-center capitalize">{{ $allocation->status->value }}</td></tr>@empty<tr><td colspan="3" class="py-5 text-center">No allocations.</td></tr>@endforelse</tbody></table></div></section>
    <div class="mt-5 flex flex-wrap gap-3">@can('update', $customerPayment)<a href="{{ route('customer-payments.edit', $customerPayment) }}" class="rounded-lg border px-4 py-2">Edit</a>@endcan
        @if($customerPayment->status === \App\Enums\CustomerPaymentStatus::Draft) @can('post', $customerPayment)<form method="POST" action="{{ route('customer-payments.transition', $customerPayment) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="posted"><button class="rounded-lg bg-blue-700 px-4 py-2 text-white">Post payment</button></form>@endcan @endif
        @if(in_array($customerPayment->status, [\App\Enums\CustomerPaymentStatus::Posted, \App\Enums\CustomerPaymentStatus::PartiallyAllocated, \App\Enums\CustomerPaymentStatus::FullyAllocated], true)) @can('void', $customerPayment)<form method="POST" action="{{ route('customer-payments.transition', $customerPayment) }}" class="flex gap-2">@csrf @method('PATCH')<input type="hidden" name="status" value="voided"><input name="reason" required placeholder="Void reason" class="rounded-lg border px-3 py-2"><button class="rounded-lg border border-red-300 px-4 py-2 text-red-700">Void</button></form>@endcan @endif
    </div>
    @if(in_array($customerPayment->status, [\App\Enums\CustomerPaymentStatus::Posted, \App\Enums\CustomerPaymentStatus::PartiallyAllocated], true) && bccomp($customerPayment->unapplied_amount, '0', 4) === 1) @can('allocate', $customerPayment)<form method="POST" action="{{ route('customer-payments.allocate', $customerPayment) }}" class="mt-5 grid gap-3 rounded-2xl bg-white p-6 ring-1 ring-slate-200 md:grid-cols-2"><h2 class="font-semibold md:col-span-2">Allocate payment</h2>@csrf <label class="grid gap-1 text-sm">Open invoice<select name="allocations[0][sales_invoice_id]" required class="rounded-lg border-slate-300"><option value="">Select invoice</option>@foreach($openInvoices as $invoice)<option value="{{ $invoice->id }}">{{ $invoice->invoice_number }} — ₱{{ number_format((float) $invoice->balance_due, 2) }}</option>@endforeach</select></label><label class="grid gap-1 text-sm">Amount<input type="number" name="allocations[0][amount]" step="0.0001" min="0.0001" required class="rounded-lg border-slate-300"></label><button class="w-fit rounded-lg bg-blue-700 px-4 py-2 text-white">Apply amount</button></form>@endcan @endif
</x-app-layout>
