<x-app-layout title="Products and Services">
    <x-page-header title="Products and Services" description="Maintain one catalog for sellable products and services." />
    <div class="mb-5 flex flex-wrap items-end justify-between gap-4">
        <form method="GET" action="{{ route('products-services.index') }}" class="flex flex-wrap items-end gap-3">
            <label class="flex flex-col gap-1 text-sm font-medium">Search<input name="search" value="{{ request('search') }}" placeholder="SKU, barcode, or name" class="rounded-lg border border-slate-300 px-3 py-2"></label>
            <label class="flex flex-col gap-1 text-sm font-medium">Type<select name="type" class="rounded-lg border border-slate-300 px-3 py-2"><option value="">All</option><option value="product" @selected(request('type') === 'product')>Product</option><option value="service" @selected(request('type') === 'service')>Service</option></select></label>
            <label class="flex flex-col gap-1 text-sm font-medium">Status<select name="status" class="rounded-lg border border-slate-300 px-3 py-2"><option value="">All</option><option value="active" @selected(request('status') === 'active')>Active</option><option value="inactive" @selected(request('status') === 'inactive')>Inactive</option></select></label>
            <button class="rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-semibold">Filter</button>
        </form>
        @can('create', \App\Models\ProductService::class)<a href="{{ route('products-services.create') }}" class="rounded-lg bg-blue-700 px-4 py-2 text-sm font-semibold text-white">Create catalog item</a>@endcan
    </div>
    <div class="overflow-x-auto rounded-2xl bg-white shadow-sm ring-1 ring-slate-200"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-slate-600"><tr><th class="px-6 py-3">SKU</th><th class="px-6 py-3">Item</th><th class="px-6 py-3">Type / Category</th><th class="px-6 py-3">UOM</th><th class="px-6 py-3">Price</th><th class="px-6 py-3">Inventory</th><th class="px-6 py-3">Status</th><th class="px-6 py-3">Action</th></tr></thead><tbody class="divide-y divide-slate-100">
    @forelse ($productServices as $productService)<tr><td class="px-6 py-4 font-mono font-medium">{{ $productService->sku }}</td><td class="px-6 py-4"><p class="font-medium">{{ $productService->name }}</p><p class="text-xs text-slate-500">{{ $productService->barcode ?: 'No barcode' }}</p></td><td class="px-6 py-4"><p class="capitalize">{{ $productService->type }}</p><p class="text-xs text-slate-500">{{ $productService->category->name }}</p></td><td class="px-6 py-4">{{ $productService->unitOfMeasure->code }}</td><td class="px-6 py-4">{{ \Illuminate\Support\Number::currency($productService->selling_price, 'PHP') }}</td><td class="px-6 py-4">{{ $productService->is_inventory ? 'Tracked' : 'No' }}</td><td class="px-6 py-4 capitalize">{{ $productService->status }}</td><td class="px-6 py-4">@can('update', $productService)<a href="{{ route('products-services.edit', $productService) }}" class="font-semibold text-blue-700">Edit</a>@endcan</td></tr>@empty<tr><td colspan="8" class="px-6 py-8 text-center text-slate-500">No products or services found.</td></tr>@endforelse
    </tbody></table></div><div class="mt-6">{{ $productServices->links() }}</div>
</x-app-layout>
