@php($editing = isset($disbursement))
<x-app-layout :title="$editing ? 'Edit Cash Disbursement' : 'Record Cash Disbursement'">
    <x-page-header :title="$editing ? 'Edit Cash Disbursement' : 'Record Cash Disbursement'" description="Save a draft before posting it to an operational account." />
    <form method="POST" action="{{ $editing ? route('cash-disbursements.update', $disbursement) : route('cash-disbursements.store') }}" class="grid gap-5 rounded-2xl bg-white p-6 ring-1 ring-slate-200 md:grid-cols-2">
        @csrf
        @if($editing) @method('PUT') @endif
        <label class="grid gap-1 text-sm">Disbursement date<input type="date" name="disbursement_date" value="{{ old('disbursement_date', $editing ? $disbursement->disbursement_date->toDateString() : now()->toDateString()) }}" required class="rounded-lg border-slate-300">@error('disbursement_date')<span class="text-red-600">{{ $message }}</span>@enderror</label>
        <label class="grid gap-1 text-sm">Fiscal period<select name="fiscal_period_id" required class="rounded-lg border-slate-300"><option value="">Select period</option>@foreach($periods as $period)<option value="{{ $period->id }}" @selected(old('fiscal_period_id', $disbursement->fiscal_period_id ?? '') == $period->id)>{{ $period->name }}</option>@endforeach</select>@error('fiscal_period_id')<span class="text-red-600">{{ $message }}</span>@enderror</label>
        <label class="grid gap-1 text-sm">Financial account<select name="financial_account_id" required class="rounded-lg border-slate-300"><option value="">Select account</option>@foreach($accounts as $account)<option value="{{ $account->id }}" @selected(old('financial_account_id', $disbursement->financial_account_id ?? '') == $account->id)>{{ $account->code }} — {{ $account->name }}</option>@endforeach</select>@error('financial_account_id')<span class="text-red-600">{{ $message }}</span>@enderror</label>
        <label class="grid gap-1 text-sm">Source type<select name="source_type" required class="rounded-lg border-slate-300">@foreach($sourceTypes as $type)<option value="{{ $type->value }}" @selected(old('source_type', $disbursement->source_type->value ?? '') === $type->value)>{{ str($type->value)->headline() }}</option>@endforeach</select>@error('source_type')<span class="text-red-600">{{ $message }}</span>@enderror</label>
        <label class="grid gap-1 text-sm">Supplier payment (when applicable)<select name="supplier_payment_id" class="rounded-lg border-slate-300"><option value="">None</option>@foreach($supplierPayments as $payment)<option value="{{ $payment->id }}" @selected(old('supplier_payment_id', $disbursement->supplier_payment_id ?? '') == $payment->id)>{{ $payment->payment_number }} — {{ $payment->supplier->name }} — PHP {{ number_format((float) $payment->net_cash_paid, 2) }}</option>@endforeach</select>@error('supplier_payment_id')<span class="text-red-600">{{ $message }}</span>@enderror</label>
        <label class="grid gap-1 text-sm">Expense (when applicable)<select name="expense_id" class="rounded-lg border-slate-300"><option value="">None</option>@foreach($expenses as $expense)<option value="{{ $expense->id }}" @selected(old('expense_id', $disbursement->expense_id ?? '') == $expense->id)>{{ $expense->expense_number }} — {{ $expense->payee_name }} — PHP {{ number_format((float) $expense->net_cash_paid, 2) }}</option>@endforeach</select>@error('expense_id')<span class="text-red-600">{{ $message }}</span>@enderror</label>
        <label class="grid gap-1 text-sm">Payee<input name="payee" value="{{ old('payee', $disbursement->payee ?? '') }}" required class="rounded-lg border-slate-300">@error('payee')<span class="text-red-600">{{ $message }}</span>@enderror</label>
        <label class="grid gap-1 text-sm">Payment method<select name="payment_method_id" required class="rounded-lg border-slate-300">@foreach($paymentMethods as $method)<option value="{{ $method->id }}" @selected(old('payment_method_id', $disbursement->payment_method_id ?? '') == $method->id)>{{ $method->name }}</option>@endforeach</select>@error('payment_method_id')<span class="text-red-600">{{ $message }}</span>@enderror</label>
        <label class="grid gap-1 text-sm">Cheque/transfer reference<input name="reference_number" value="{{ old('reference_number', $disbursement->reference_number ?? '') }}" class="rounded-lg border-slate-300"></label>
        @foreach(['gross_settlement' => 'Gross settlement', 'deductions_or_bank_charges' => 'Deductions or bank charges', 'net_cash_out' => 'Net cash out'] as $field => $label)
            <label class="grid gap-1 text-sm">{{ $label }}<input type="number" step="0.0001" min="0" name="{{ $field }}" value="{{ old($field, $disbursement->{$field} ?? '0.0000') }}" required class="rounded-lg border-slate-300">@error($field)<span class="text-red-600">{{ $message }}</span>@enderror</label>
        @endforeach
        <label class="grid gap-1 text-sm md:col-span-2">Notes<textarea name="notes" rows="3" class="rounded-lg border-slate-300">{{ old('notes', $disbursement->notes ?? '') }}</textarea></label>
        <button class="w-fit rounded-lg bg-blue-700 px-4 py-2 font-semibold text-white">Save draft</button>
    </form>
</x-app-layout>
