<x-app-layout title="Warehouse Transfer">
    <x-page-header :title="$transfer->transfer_number ?? 'Draft #'.$transfer->id" :description="$transfer->sourceWarehouse->code.' to '.$transfer->destinationWarehouse->code" />
    <div class="mb-5 flex flex-wrap justify-end gap-3">
        @php($next = match($transfer->status) { \App\Enums\InventoryTransferStatus::Draft => ['approved', 'Approve', 'approve'], \App\Enums\InventoryTransferStatus::Approved => ['released', 'Release stock', 'release'], \App\Enums\InventoryTransferStatus::Released => ['in_transit', 'Mark in transit', 'release'], \App\Enums\InventoryTransferStatus::InTransit => ['received', 'Receive stock', 'receive'], \App\Enums\InventoryTransferStatus::Received => ['completed', 'Complete', 'receive'], default => null })
        @if($next)@can($next[2], $transfer)<form method="POST" action="{{ route('inventory-transfers.transition', $transfer) }}" onsubmit="return confirm('{{ $next[1] }}?')">@csrf @method('PATCH')<input type="hidden" name="status" value="{{ $next[0] }}"><button class="rounded-lg bg-blue-700 px-4 py-2 text-sm font-semibold text-white">{{ $next[1] }}</button></form>@endcan @endif
        @if($transfer->status !== \App\Enums\InventoryTransferStatus::Voided)@can('void', $transfer)<form method="POST" action="{{ route('inventory-transfers.transition', $transfer) }}" class="flex flex-wrap gap-2" onsubmit="return confirm('Void through reversal movements?')">@csrf @method('PATCH')<input type="hidden" name="status" value="voided"><input name="reason" required maxlength="1000" placeholder="Void reason" class="rounded-lg border-slate-300"><button class="rounded-lg bg-red-700 px-4 py-2 text-sm font-semibold text-white">Void</button></form>@endcan @endif
    </div>
    <dl class="grid gap-4 rounded-2xl bg-white p-6 text-sm ring-1 ring-slate-200 md:grid-cols-4"><div><dt class="text-slate-500">Date</dt><dd class="font-semibold">{{ $transfer->transfer_date->format('M d, Y') }}</dd></div><div><dt class="text-slate-500">Source</dt><dd class="font-semibold">{{ $transfer->sourceWarehouse->code }}</dd></div><div><dt class="text-slate-500">Destination</dt><dd class="font-semibold">{{ $transfer->destinationWarehouse->code }}</dd></div><div><dt class="text-slate-500">Status</dt><dd class="font-semibold">{{ str($transfer->status->value)->headline() }}</dd></div></dl>
    <div class="mt-6 overflow-x-auto rounded-2xl bg-white ring-1 ring-slate-200"><table class="min-w-full text-sm"><thead><tr><th class="px-5 py-3 text-left">Product</th><th class="text-right">Quantity</th><th class="text-right">Source cost</th><th class="pr-5 text-right">Total cost</th></tr></thead><tbody>@foreach($transfer->lines as $line)<tr class="border-t"><td class="px-5 py-3">{{ $line->product->sku }} — {{ $line->product->name }}</td><td class="text-right">{{ number_format((float) $line->quantity, 4) }}</td><td class="text-right">{{ $line->source_unit_cost === null ? 'At release' : 'PHP '.number_format((float) $line->source_unit_cost, 4) }}</td><td class="pr-5 text-right font-semibold">{{ $line->total_cost === null ? 'At release' : 'PHP '.number_format((float) $line->total_cost, 4) }}</td></tr>@endforeach</tbody></table></div>
    @if($transfer->void_reason)<p class="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-800"><strong>Void reason:</strong> {{ $transfer->void_reason }}</p>@endif
</x-app-layout>
