@php $entry ??= null; $rows = old('lines', $entry?->lines?->toArray() ?? [['debit' => '0.0000', 'credit' => '0.0000'], ['debit' => '0.0000', 'credit' => '0.0000']]); @endphp
<x-app-layout :title="$entry ? 'Edit Journal Entry' : 'Create Journal Entry'">
    <x-page-header :title="$entry ? 'Edit Journal Entry' : 'Create Journal Entry'" description="Draft totals are calculated on the server. Each line must be debit or credit only." />
    <form method="POST" action="{{ $entry ? route('journal-entries.update', $entry) : route('journal-entries.store') }}" class="flex flex-col gap-5">@csrf @if($entry) @method('PUT') @endif
        <div class="grid gap-4 rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200 md:grid-cols-2 lg:grid-cols-3">
            <label class="flex flex-col gap-1 text-sm font-medium">Journal number<input name="journal_number" required value="{{ old('journal_number', $entry?->journal_number) }}" class="rounded-lg border border-slate-300 px-3 py-2">@error('journal_number')<span class="text-red-700">{{ $message }}</span>@enderror</label>
            <label class="flex flex-col gap-1 text-sm font-medium">Journal date<input type="date" name="journal_date" required value="{{ old('journal_date', $entry?->journal_date?->format('Y-m-d')) }}" class="rounded-lg border border-slate-300 px-3 py-2">@error('journal_date')<span class="text-red-700">{{ $message }}</span>@enderror</label>
            <label class="flex flex-col gap-1 text-sm font-medium">Document date<input type="date" name="document_date" required value="{{ old('document_date', $entry?->document_date?->format('Y-m-d')) }}" class="rounded-lg border border-slate-300 px-3 py-2">@error('document_date')<span class="text-red-700">{{ $message }}</span>@enderror</label>
            <label class="flex flex-col gap-1 text-sm font-medium">Fiscal period<select name="fiscal_period_id" class="rounded-lg border border-slate-300 px-3 py-2">@foreach($periods as $period)<option value="{{ $period->id }}" @selected((string)old('fiscal_period_id', $entry?->fiscal_period_id)===(string)$period->id)>{{ $period->name }}</option>@endforeach</select>@error('fiscal_period_id')<span class="text-red-700">{{ $message }}</span>@enderror</label>
            <label class="flex flex-col gap-1 text-sm font-medium">Journal type<select name="journal_type" class="rounded-lg border border-slate-300 px-3 py-2">@foreach($journalTypes as $type)<option value="{{ $type->value }}" @selected(old('journal_type', $entry?->journal_type?->value ?? 'adjustment')===$type->value)>{{ str($type->value)->headline() }}</option>@endforeach</select></label>
            <label class="flex flex-col gap-1 text-sm font-medium">Source type<select name="source_type" class="rounded-lg border border-slate-300 px-3 py-2">@foreach($sourceTypes as $type)<option value="{{ $type->value }}" @selected(old('source_type', $entry?->source_type?->value ?? 'manual')===$type->value)>{{ str($type->value)->headline() }}</option>@endforeach</select></label>
            <label class="flex flex-col gap-1 text-sm font-medium">Source ID<input type="number" name="source_id" value="{{ old('source_id', $entry?->source_id) }}" class="rounded-lg border border-slate-300 px-3 py-2">@error('source_id')<span class="text-red-700">{{ $message }}</span>@enderror</label>
            <label class="flex flex-col gap-1 text-sm font-medium">Reference<input name="reference_number" value="{{ old('reference_number', $entry?->reference_number) }}" class="rounded-lg border border-slate-300 px-3 py-2"></label>
            <label class="flex flex-col gap-1 text-sm font-medium lg:col-span-3">Description<textarea name="description" required class="rounded-lg border border-slate-300 px-3 py-2">{{ old('description', $entry?->description) }}</textarea></label>
        </div>
        <div class="overflow-x-auto rounded-2xl bg-white shadow-sm ring-1 ring-slate-200"><table class="min-w-full text-sm"><thead class="bg-slate-50"><tr><th class="px-4 py-3 text-left">Account</th><th class="px-4 py-3 text-left">Description</th><th class="px-4 py-3 text-right">Debit</th><th class="px-4 py-3 text-right">Credit</th></tr></thead><tbody class="divide-y divide-slate-100">
            @foreach($rows as $index => $row)<tr><td class="px-4 py-3"><select name="lines[{{ $index }}][account_id]" class="w-full rounded-lg border border-slate-300 px-3 py-2">@foreach($accounts as $account)<option value="{{ $account->id }}" @selected((string)($row['account_id'] ?? '')===(string)$account->id)>{{ $account->code }} — {{ $account->name }}</option>@endforeach</select>@error("lines.$index.account_id")<span class="block text-red-700">{{ $message }}</span>@enderror</td><td class="px-4 py-3"><input name="lines[{{ $index }}][description]" value="{{ $row['description'] ?? '' }}" class="w-full rounded-lg border border-slate-300 px-3 py-2"></td><td class="px-4 py-3"><input name="lines[{{ $index }}][debit]" value="{{ $row['debit'] ?? '0.0000' }}" class="w-36 rounded-lg border border-slate-300 px-3 py-2 text-right font-mono">@error("lines.$index.debit")<span class="block text-red-700">{{ $message }}</span>@enderror</td><td class="px-4 py-3"><input name="lines[{{ $index }}][credit]" value="{{ $row['credit'] ?? '0.0000' }}" class="w-36 rounded-lg border border-slate-300 px-3 py-2 text-right font-mono"></td></tr>@endforeach
        </tbody></table></div>
        <div class="flex gap-3"><button class="rounded-lg bg-blue-700 px-4 py-2 text-sm font-semibold text-white">Save draft</button><a href="{{ route('journal-entries.index') }}" class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold">Cancel</a></div>
    </form>
</x-app-layout>
