<x-app-layout title="Sales Invoice">
    <x-page-header title="{{ $invoice->invoice_number ?? 'Draft #'.$invoice->id }}" description="{{ ucfirst(str_replace('_', ' ', $invoice->status->value)) }} invoice for {{ $invoice->customer_name }}" />
    <div class="grid gap-5 lg:grid-cols-3">
        <section class="rounded-2xl bg-white p-6 ring-1 ring-slate-200 lg:col-span-2"><p class="font-semibold">{{ $invoice->customer_name }}</p><p>{{ $invoice->customer_tin ?: 'No TIN' }}</p><p class="whitespace-pre-line">{{ $invoice->billing_address }}</p>
            <table class="mt-5 w-full text-sm"><thead><tr><th class="text-left">Description</th><th>Quantity</th><th class="text-right">Net</th></tr></thead><tbody>@foreach ($invoice->lines as $line)<tr class="border-t"><td class="py-3">{{ $line->description }}</td><td class="text-center">{{ $line->quantity }} {{ $line->uom_code }}</td><td class="text-right">₱{{ number_format((float) $line->net_amount, 2) }}</td></tr>@endforeach</tbody></table>
        </section>
        <section class="rounded-2xl bg-white p-6 ring-1 ring-slate-200"><dl class="grid grid-cols-2 gap-3 text-sm"><dt>Gross</dt><dd class="text-right">₱{{ number_format((float) $invoice->gross_amount, 2) }}</dd><dt>Discount</dt><dd class="text-right">₱{{ number_format((float) $invoice->discount_amount, 2) }}</dd><dt>Net sales</dt><dd class="text-right">₱{{ number_format((float) $invoice->net_sales_amount, 2) }}</dd><dt>Expected withholding</dt><dd class="text-right">₱{{ number_format((float) $invoice->expected_withholding_amount, 2) }}</dd><dt class="font-bold">Receivable</dt><dd class="text-right font-bold">₱{{ number_format((float) $invoice->total_receivable, 2) }}</dd><dt>Paid</dt><dd class="text-right">₱{{ number_format((float) $invoice->paid_amount, 2) }}</dd><dt>Balance</dt><dd class="text-right">₱{{ number_format((float) $invoice->balance_due, 2) }}</dd></dl></section>
    </div>
    <div class="mt-5 flex flex-wrap gap-3">
        @can('print', $invoice)<a href="{{ route('sales-invoices.print', $invoice) }}" class="rounded-lg border px-4 py-2">Print</a>@endcan
        @can('update', $invoice)<a href="{{ route('sales-invoices.edit', $invoice) }}" class="rounded-lg border px-4 py-2">Edit</a>@endcan
        @if ($invoice->status === \App\Enums\SalesInvoiceStatus::Draft) @can('post', $invoice)<form method="POST" action="{{ route('sales-invoices.transition', $invoice) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="posted"><button class="rounded-lg bg-blue-700 px-4 py-2 text-white">Post invoice</button></form>@endcan @endif
        @if (in_array($invoice->status, [\App\Enums\SalesInvoiceStatus::Posted, \App\Enums\SalesInvoiceStatus::PartiallyPaid, \App\Enums\SalesInvoiceStatus::Overdue], true)) @can('void', $invoice)<form method="POST" action="{{ route('sales-invoices.transition', $invoice) }}" class="flex gap-2">@csrf @method('PATCH')<input type="hidden" name="status" value="voided"><input name="reason" required placeholder="Void reason" class="rounded-lg border px-3 py-2"><button class="rounded-lg border border-red-300 px-4 py-2 text-red-700">Void</button></form>@endcan @endif
    </div>
<x-sales-record-panel :record="$invoice" />
</x-app-layout>
