@php($editing = isset($deduction))
<x-app-layout :title="$editing ? 'Edit Government Deduction' : 'Record Government Deduction'">
    <x-page-header :title="$editing ? 'Edit Government Deduction' : 'Record Government Deduction'" description="The amount is calculated from the effective-dated configured rate." />
    <form method="POST" action="{{ $editing ? route('government-deductions.update', $deduction) : route('government-deductions.store') }}" class="grid gap-5 rounded-2xl bg-white p-6 ring-1 ring-slate-200 md:grid-cols-2">@csrf @if($editing) @method('PUT') @endif
        <label class="grid gap-1 text-sm">Government invoice<select name="sales_invoice_id" required class="rounded-lg border-slate-300"><option value="">Select invoice</option>@foreach($invoices as $invoice)<option value="{{ $invoice->id }}" @selected(old('sales_invoice_id', $deduction->sales_invoice_id ?? request('sales_invoice_id')) == $invoice->id)>{{ $invoice->invoice_number }} — {{ $invoice->customer_name }} — ₱{{ number_format((float)$invoice->gross_amount, 2) }}</option>@endforeach</select>@error('sales_invoice_id')<span class="text-red-600">{{ $message }}</span>@enderror</label>
        <label class="grid gap-1 text-sm">Related payment (optional)<select name="customer_payment_id" class="rounded-lg border-slate-300"><option value="">None</option>@foreach($payments as $payment)<option value="{{ $payment->id }}" @selected(old('customer_payment_id', $deduction->customer_payment_id ?? '') == $payment->id)>{{ $payment->payment_number }} — {{ $payment->payment_date->toDateString() }}</option>@endforeach</select>@error('customer_payment_id')<span class="text-red-600">{{ $message }}</span>@enderror</label>
        <label class="grid gap-1 text-sm">Deduction type<select name="deduction_type" required class="rounded-lg border-slate-300">@foreach(\App\Models\GovernmentDeduction::DEDUCTION_TYPES as $type)<option value="{{ $type }}" @selected(old('deduction_type', $deduction->deduction_type ?? '') === $type)>{{ str_replace('_', ' ', ucfirst($type)) }}</option>@endforeach</select>@error('deduction_type')<span class="text-red-600">{{ $message }}</span>@enderror</label>
        <label class="grid gap-1 text-sm">Configured rate<select name="tax_rate_setting_id" required class="rounded-lg border-slate-300"><option value="">Select rate</option>@foreach($rates as $rate)<option value="{{ $rate->id }}" @selected(old('tax_rate_setting_id', $deduction->tax_rate_setting_id ?? '') == $rate->id)>{{ str_replace('_', ' ', $rate->tax_type) }} — {{ $rate->rate }}% ({{ $rate->effective_from->toDateString() }})</option>@endforeach</select>@error('tax_rate_setting_id')<span class="text-red-600">{{ $message }}</span>@enderror</label>
        <label class="grid gap-1 text-sm">Certificate type<select name="certificate_type" required class="rounded-lg border-slate-300">@foreach(\App\Models\GovernmentDeduction::CERTIFICATE_TYPES as $type)<option value="{{ $type }}" @selected(old('certificate_type', $deduction->certificate_type ?? '') === $type)>{{ $type }}</option>@endforeach</select></label>
        <label class="grid gap-1 text-sm">Certificate number<input name="certificate_number" value="{{ old('certificate_number', $deduction->certificate_number ?? '') }}" class="rounded-lg border-slate-300">@error('certificate_number')<span class="text-red-600">{{ $message }}</span>@enderror</label>
        <label class="grid gap-1 text-sm">Certificate date<input type="date" name="certificate_date" value="{{ old('certificate_date', isset($deduction) ? $deduction->certificate_date?->toDateString() : '') }}" class="rounded-lg border-slate-300">@error('certificate_date')<span class="text-red-600">{{ $message }}</span>@enderror</label>
        <label class="grid gap-1 text-sm">Gross basis<input type="number" step="0.0001" min="0.0001" name="gross_basis" value="{{ old('gross_basis', $deduction->gross_basis ?? '') }}" required class="rounded-lg border-slate-300">@error('gross_basis')<span class="text-red-600">{{ $message }}</span>@enderror</label>
        <label class="grid gap-1 text-sm">Covered from<input type="date" name="covered_from" value="{{ old('covered_from', isset($deduction) ? $deduction->covered_from->toDateString() : '') }}" required class="rounded-lg border-slate-300"></label><label class="grid gap-1 text-sm">Covered to<input type="date" name="covered_to" value="{{ old('covered_to', isset($deduction) ? $deduction->covered_to->toDateString() : '') }}" required class="rounded-lg border-slate-300">@error('covered_to')<span class="text-red-600">{{ $message }}</span>@enderror</label>
        <label class="grid gap-1 text-sm">Attachment reference<input name="attachment_reference" value="{{ old('attachment_reference', $deduction->attachment_reference ?? '') }}" class="rounded-lg border-slate-300"></label><label class="grid gap-1 text-sm">Notes<textarea name="notes" class="rounded-lg border-slate-300">{{ old('notes', $deduction->notes ?? '') }}</textarea></label>
        <div class="md:col-span-2"><button class="rounded-lg bg-blue-700 px-4 py-2 font-semibold text-white">Save deduction</button></div>
    </form>
</x-app-layout>
