<x-app-layout title="Government Deduction">
    <x-page-header title="{{ $deduction->salesInvoice->invoice_number }} — {{ str_replace('_', ' ', ucfirst($deduction->deduction_type)) }}" description="{{ ucfirst($deduction->status->value) }} certificate tracking for {{ $deduction->customer->name }}." />
    <div class="grid gap-5 lg:grid-cols-2"><section class="rounded-2xl bg-white p-6 ring-1 ring-slate-200"><dl class="grid grid-cols-2 gap-3 text-sm"><dt>Invoice gross</dt><dd class="text-right">₱{{ number_format((float)$deduction->salesInvoice->gross_amount, 2) }}</dd><dt>Gross basis</dt><dd class="text-right">₱{{ number_format((float)$deduction->gross_basis, 2) }}</dd><dt>Configured rate</dt><dd class="text-right">{{ $deduction->rate }}%</dd><dt class="font-bold">Deduction</dt><dd class="text-right font-bold">₱{{ number_format((float)$deduction->amount, 2) }}</dd><dt>Net after deduction</dt><dd class="text-right">₱{{ number_format((float)$deduction->netAfterDeduction(), 2) }}</dd></dl></section><section class="rounded-2xl bg-white p-6 ring-1 ring-slate-200"><dl class="grid grid-cols-2 gap-3 text-sm"><dt>Certificate</dt><dd>{{ $deduction->certificate_type }}</dd><dt>Number</dt><dd>{{ $deduction->certificate_number ?: 'Missing' }}</dd><dt>Date</dt><dd>{{ $deduction->certificate_date?->format('M d, Y') ?? 'Missing' }}</dd><dt>Covered period</dt><dd>{{ $deduction->covered_from->toDateString() }} to {{ $deduction->covered_to->toDateString() }}</dd><dt>Attachment</dt><dd>{{ $deduction->attachment_reference ?: 'None' }}</dd></dl></section></div>
    <div class="mt-5 flex flex-wrap gap-3">@can('update', $deduction)<a href="{{ route('government-deductions.edit', $deduction) }}" class="rounded-lg border px-4 py-2">Edit</a>@endcan @if($deduction->status === \App\Enums\GovernmentDeductionStatus::Received) @can('verify', $deduction)<form method="POST" action="{{ route('government-deductions.transition', $deduction) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="verified"><button class="rounded-lg bg-blue-700 px-4 py-2 text-white">Verify certificate</button></form>@endcan @endif @if($deduction->status !== \App\Enums\GovernmentDeductionStatus::Voided) @can('void', $deduction)<form method="POST" action="{{ route('government-deductions.transition', $deduction) }}" class="flex gap-2">@csrf @method('PATCH')<input type="hidden" name="status" value="voided"><input name="reason" required placeholder="Void reason" class="rounded-lg border px-3 py-2"><button class="rounded-lg border border-red-300 px-4 py-2 text-red-700">Void</button></form>@endcan @endif</div>
    @if(in_array($deduction->status, [\App\Enums\GovernmentDeductionStatus::Pending, \App\Enums\GovernmentDeductionStatus::Received, \App\Enums\GovernmentDeductionStatus::Verified], true)) @can('reject', $deduction)<form method="POST" action="{{ route('government-deductions.transition', $deduction) }}" class="mt-4 flex flex-wrap gap-2">@csrf @method('PATCH')<input type="hidden" name="status" value="rejected"><input name="reason" required placeholder="Rejection reason" class="rounded-lg border-slate-300"><button class="rounded-lg border border-amber-400 px-4 py-2 text-amber-800">Reject certificate</button></form>@endcan @endif
    <section class="mt-6 rounded-2xl bg-white p-6 ring-1 ring-slate-200"><h2 class="font-semibold">Tax-credit applications</h2><dl class="mt-4 grid grid-cols-2 gap-3 text-sm"><dt>Applied</dt><dd class="text-right">₱{{ number_format((float)$deduction->appliedAmount(), 4) }}</dd><dt>Remaining</dt><dd class="text-right font-semibold">₱{{ number_format((float)$deduction->remainingAmount(), 4) }}</dd><dt>Accounting entry</dt><dd class="text-right">{{ $deduction->journalEntryLine?->journalEntry?->journal_number ?? 'Not matched' }}</dd></dl>
        @if(in_array($deduction->status, [\App\Enums\GovernmentDeductionStatus::Verified, \App\Enums\GovernmentDeductionStatus::Applied], true) && bccomp($deduction->remainingAmount(), '0.0000', 4) > 0) @can('apply', $deduction)<form method="POST" action="{{ route('government-deductions.applications.store', $deduction) }}" class="mt-5 grid gap-3 md:grid-cols-2">@csrf<label class="grid gap-1 text-sm">Return<select name="tax_obligation_id" required class="rounded-lg border-slate-300"><option value="">Select return</option>@foreach($obligations as $obligation)<option value="{{ $obligation->id }}">{{ $obligation->bir_form_number }} · {{ $obligation->taxPeriod->label }}</option>@endforeach</select></label><label class="grid gap-1 text-sm">Amount<input name="amount" required inputmode="decimal" value="{{ $deduction->remainingAmount() }}" class="rounded-lg border-slate-300"></label><label class="grid gap-1 text-sm">Evidence reference<input name="evidence_reference" required class="rounded-lg border-slate-300"></label><label class="grid gap-1 text-sm">Notes<input name="notes" class="rounded-lg border-slate-300"></label><div class="md:col-span-2"><button class="rounded-lg bg-emerald-700 px-4 py-2 font-medium text-white">Apply tax credit</button></div></form>@endcan @endif
        @if($deduction->applications->isNotEmpty())<div class="mt-5 overflow-x-auto"><table class="min-w-full text-sm"><thead><tr><th class="py-2 text-left">Return</th><th class="py-2 text-right">Amount</th><th class="py-2 text-left">Evidence</th></tr></thead><tbody>@foreach($deduction->applications as $application)<tr><td class="py-2">{{ $application->taxObligation->bir_form_number }} · {{ $application->taxObligation->taxPeriod->label }}</td><td class="py-2 text-right">₱{{ number_format((float)$application->amount, 4) }}</td><td class="py-2">{{ $application->evidence_reference }}</td></tr>@endforeach</tbody></table></div>@endif
    </section>
<x-sales-record-panel :record="$deduction" />
</x-app-layout>
