<x-app-layout title="Tax Reconciliation">
    @php($snapshot = $reconciliation->source_snapshot)
    <div class="flex flex-col gap-6">
        <div class="flex flex-wrap items-start justify-between gap-4">
            <div><h1 class="text-2xl font-semibold text-slate-900">{{ $reconciliation->taxObligation->taxPeriod->label }} sales reconciliation</h1><p class="mt-1 text-sm text-slate-600">Tax-base rule: {{ $reconciliation->tax_base_rule }}</p></div>
            <div class="flex gap-2"><a class="rounded-lg border border-slate-300 px-3 py-2 text-sm font-medium" href="{{ route('tax-reconciliations.index') }}">Back</a>@can('export', $reconciliation)<a class="rounded-lg bg-slate-900 px-3 py-2 text-sm font-medium text-white" href="{{ route('tax-reconciliations.export', $reconciliation) }}">Export CSV</a>@endcan</div>
        </div>

        <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
            @foreach(['Gross sales' => 'gross_sales', 'Credit adjustments' => 'credit_adjustments', 'Operational net sales' => 'operational_net_sales', 'Receipt basis' => 'receipt_basis', 'Ledger revenue' => 'ledger_revenue', 'Customer withholding' => 'customer_withholding', 'Approved adjustments' => 'approved_adjustments', 'Difference' => 'difference'] as $label => $field)
                <div class="rounded-2xl bg-white p-4 ring-1 ring-slate-200"><p class="text-xs font-semibold uppercase tracking-wide text-slate-500">{{ $label }}</p><p class="mt-2 text-xl font-semibold text-slate-900">PHP {{ number_format((float) $reconciliation->{$field}, 4) }}</p></div>
            @endforeach
        </div>

        <div class="rounded-2xl p-4 ring-1 {{ $reconciliation->critical_difference_count ? 'bg-red-50 ring-red-200' : 'bg-emerald-50 ring-emerald-200' }}"><p class="font-semibold">{{ $reconciliation->critical_difference_count ? $reconciliation->critical_difference_count.' critical item(s) must be resolved before ready-to-file.' : 'No critical reconciliation differences.' }}</p><p class="mt-1 text-sm">Accrual and cash/receipt comparisons are shown independently and do not determine tax treatment.</p></div>

        <div class="grid gap-4 lg:grid-cols-2">
            <section class="rounded-2xl bg-white p-5 ring-1 ring-slate-200"><h2 class="font-semibold text-slate-900">Sales mix</h2><dl class="mt-4 grid grid-cols-2 gap-3 text-sm">@foreach(['Government sales' => 'government_sales', 'Private sales' => 'private_sales', 'Cash sales' => 'cash_sales', 'Credit sales' => 'credit_sales'] as $label => $field)<div><dt class="text-slate-500">{{ $label }}</dt><dd class="font-semibold">PHP {{ number_format((float) data_get($snapshot, 'summary.'.$field, 0), 4) }}</dd></div>@endforeach</dl></section>
            <section class="rounded-2xl bg-white p-5 ring-1 ring-slate-200"><h2 class="font-semibold text-slate-900">Control exceptions</h2><dl class="mt-4 grid gap-2 text-sm"><div class="flex justify-between"><dt>Missing invoice numbers</dt><dd>{{ count(data_get($snapshot, 'invoice_sequence.missing', [])) }}</dd></div><div class="flex justify-between"><dt>Normalized duplicates</dt><dd>{{ count(data_get($snapshot, 'invoice_sequence.duplicates', [])) }}</dd></div><div class="flex justify-between"><dt>Unposted invoices</dt><dd>{{ count(data_get($snapshot, 'unposted.invoice_ids', [])) }}</dd></div><div class="flex justify-between"><dt>Unposted journals</dt><dd>{{ count(data_get($snapshot, 'unposted.journal_ids', [])) }}</dd></div></dl></section>
        </div>

        <section class="overflow-hidden rounded-2xl bg-white ring-1 ring-slate-200"><div class="p-5"><h2 class="font-semibold text-slate-900">Issued and voided invoices</h2></div><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50"><tr><th class="px-4 py-3 text-left">Date</th><th class="px-4 py-3 text-left">Invoice</th><th class="px-4 py-3 text-left">Customer</th><th class="px-4 py-3 text-right">Gross</th><th class="px-4 py-3 text-right">Credit adjustment</th><th class="px-4 py-3 text-left">Status</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach(array_merge(data_get($snapshot, 'issued_invoices', []), data_get($snapshot, 'voided_invoices', [])) as $invoice)<tr><td class="px-4 py-3">{{ $invoice['date'] }}</td><td class="px-4 py-3">@can('sales-invoices.view')<a class="font-medium text-blue-700" href="{{ route('sales-invoices.show', $invoice['id']) }}">{{ $invoice['number'] }}</a>@else{{ $invoice['number'] }}@endcan</td><td class="px-4 py-3">{{ ucfirst($invoice['customer_type']) }}</td><td class="px-4 py-3 text-right">{{ number_format((float) $invoice['gross'], 4) }}</td><td class="px-4 py-3 text-right">{{ number_format((float) $invoice['credit_adjustment'], 4) }}</td><td class="px-4 py-3">{{ str($invoice['status'])->headline() }}</td></tr>@endforeach</tbody></table></div></section>

        <div class="grid gap-4 xl:grid-cols-2">
            <section class="overflow-hidden rounded-2xl bg-white ring-1 ring-slate-200"><div class="p-5"><h2 class="font-semibold text-slate-900">Collections</h2></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50"><tr><th class="px-4 py-3 text-left">Receipt</th><th class="px-4 py-3 text-right">Gross</th><th class="px-4 py-3 text-right">Withholding</th></tr></thead><tbody>@foreach(data_get($snapshot, 'collections', []) as $collection)<tr><td class="px-4 py-3">@can('customer-payments.view')<a class="font-medium text-blue-700" href="{{ route('customer-payments.show', $collection['id']) }}">{{ $collection['number'] }}</a>@else{{ $collection['number'] }}@endcan</td><td class="px-4 py-3 text-right">{{ number_format((float) $collection['gross'], 4) }}</td><td class="px-4 py-3 text-right">{{ number_format((float) $collection['withholding'], 4) }}</td></tr>@endforeach</tbody></table></div></section>
            <section class="overflow-hidden rounded-2xl bg-white ring-1 ring-slate-200"><div class="p-5"><h2 class="font-semibold text-slate-900">Revenue accounts</h2></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50"><tr><th class="px-4 py-3 text-left">Journal / account</th><th class="px-4 py-3 text-right">Debit</th><th class="px-4 py-3 text-right">Credit</th></tr></thead><tbody>@foreach(data_get($snapshot, 'revenue_lines', []) as $line)<tr><td class="px-4 py-3">@can('journals.view')<a class="font-medium text-blue-700" href="{{ route('journal-entries.show', $line['journal_entry_id']) }}">{{ $line['journal_number'] }}</a>@else{{ $line['journal_number'] }}@endcan · {{ $line['account_code'] }} {{ $line['account_name'] }}</td><td class="px-4 py-3 text-right">{{ number_format((float) $line['debit'], 4) }}</td><td class="px-4 py-3 text-right">{{ number_format((float) $line['credit'], 4) }}</td></tr>@endforeach</tbody></table></div></section>
        </div>

        <section class="rounded-2xl bg-white p-5 ring-1 ring-slate-200"><h2 class="font-semibold text-slate-900">Manual reconciliation adjustments</h2>
            <div class="mt-4 flex flex-col gap-3">@forelse($reconciliation->adjustments as $adjustment)<div class="rounded-xl bg-slate-50 p-4 text-sm"><div class="flex flex-wrap justify-between gap-2"><p class="font-semibold">PHP {{ number_format((float) $adjustment->amount, 4) }} — {{ str($adjustment->status)->headline() }}</p><p>Reviewer: {{ $adjustment->reviewer->name }}</p></div><p class="mt-2">{{ $adjustment->reason }}</p><p class="mt-1 text-slate-500">Evidence: {{ $adjustment->evidence_reference }}</p>@can('review', $reconciliation)@if($adjustment->status === 'pending')<form method="POST" action="{{ route('tax-reconciliations.adjustments.review', $adjustment) }}" class="mt-3 flex flex-wrap gap-2">@csrf @method('PATCH')<input class="min-w-56 flex-1 rounded-lg border-slate-300" name="review_notes" placeholder="Review notes"><button name="status" value="approved" class="rounded-lg bg-emerald-700 px-3 py-2 text-white">Approve</button><button name="status" value="rejected" class="rounded-lg bg-red-700 px-3 py-2 text-white">Reject</button></form>@endif@endcan</div>@empty<p class="text-sm text-slate-500">No manual adjustments.</p>@endforelse</div>
            @can('adjust', $reconciliation)<form method="POST" action="{{ route('tax-reconciliations.adjustments.store', $reconciliation) }}" class="mt-5 grid gap-3 md:grid-cols-2">@csrf<div><label class="text-sm font-medium">Amount</label><input name="amount" value="{{ old('amount') }}" class="mt-1 w-full rounded-lg border-slate-300">@error('amount')<p class="text-sm text-red-600">{{ $message }}</p>@enderror</div><div><label class="text-sm font-medium">Reviewer</label><select name="reviewer_id" class="mt-1 w-full rounded-lg border-slate-300"><option value="">Select reviewer</option>@foreach($reviewers as $reviewer)<option value="{{ $reviewer->id }}" @selected(old('reviewer_id') == $reviewer->id)>{{ $reviewer->name }}</option>@endforeach</select>@error('reviewer_id')<p class="text-sm text-red-600">{{ $message }}</p>@enderror</div><div><label class="text-sm font-medium">Reason</label><textarea name="reason" class="mt-1 w-full rounded-lg border-slate-300">{{ old('reason') }}</textarea>@error('reason')<p class="text-sm text-red-600">{{ $message }}</p>@enderror</div><div><label class="text-sm font-medium">Evidence reference</label><input name="evidence_reference" value="{{ old('evidence_reference') }}" class="mt-1 w-full rounded-lg border-slate-300">@error('evidence_reference')<p class="text-sm text-red-600">{{ $message }}</p>@enderror</div><div class="md:col-span-2"><button class="rounded-lg bg-slate-900 px-4 py-2 text-sm font-medium text-white">Submit adjustment</button></div></form>@endcan
        </section>
    </div>
</x-app-layout>
