<?php

namespace App\Http\Controllers;

use App\Http\Requests\BooksAndSchedulesReportRequest;
use App\Models\BusinessProfile;
use App\Models\FiscalYear;
use App\Models\TaxPeriod;
use App\Services\BooksAndSchedules;
use Illuminate\View\View;
use Symfony\Component\HttpFoundation\StreamedResponse;

class BooksAndSchedulesController extends Controller
{
    public function __construct(private BooksAndSchedules $reports) {}

    public function index(BooksAndSchedulesReportRequest $request): View
    {
        return view('books-and-schedules.index', $this->data($request));
    }

    public function print(BooksAndSchedulesReportRequest $request): View
    {
        return view('books-and-schedules.print', $this->data($request));
    }

    public function export(BooksAndSchedulesReportRequest $request): StreamedResponse
    {
        $data = $this->data($request);
        $businessName = $data['business'] instanceof BusinessProfile ? $data['business']->registered_business_name : 'Business identity missing';

        return response()->streamDownload(function () use ($businessName, $data): void {
            $stream = fopen('php://output', 'w');
            fputcsv($stream, [$businessName, $data['label']]);
            fputcsv($stream, ['Period', $data['filters']['start_date'].' to '.$data['filters']['end_date'], 'Classification', $data['classification']]);
            if ($data['balances']) {
                fputcsv($stream, ['Beginning balance', $data['balances']['beginning'], 'Ending balance', $data['balances']['ending']]);
            }
            fputcsv($stream, ['Generated by', $data['generated_by'], 'Generated at', $data['generated_at']->toIso8601String()]);
            fputcsv($stream, [$data['disclaimer']]);
            fputcsv($stream, []);
            fputcsv($stream, $data['headers']);
            foreach ($data['rows'] as $row) {
                fputcsv($stream, array_values($row));
            }
            if ($data['totals'] !== []) {
                fputcsv($stream, []);
                foreach ($data['totals'] as $label => $amount) {
                    fputcsv($stream, ['Total '.$label, $amount]);
                }
            }
            fclose($stream);
        }, str($data['report'])->replace('_', '-').'-'.$data['filters']['end_date'].'.csv', ['Content-Type' => 'text/csv']);
    }

    /** @return array<string, mixed> */
    private function data(BooksAndSchedulesReportRequest $request): array
    {
        return $this->reports->generate($request->validated(), $request->user()) + [
            'reports' => BooksAndSchedules::REPORTS, 'fiscalYears' => FiscalYear::query()->latest('starts_on')->get(['id', 'name']),
            'taxPeriods' => TaxPeriod::query()->latest('period_end')->get(['id', 'label']),
        ];
    }
}
