<x-app-layout title="Privacy and retention">
    <x-page-header title="Privacy and retention" description="Data classification, retention review, and controlled data-subject lookup." />
    <section class="grid gap-4 md:grid-cols-2 xl:grid-cols-4">@foreach($classifications as $level => $classification)<article class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 class="font-semibold capitalize">{{ $level }}</h2><p class="mt-1 text-sm text-slate-600">{{ $classification['description'] }}</p><p class="mt-3 text-xs font-semibold uppercase text-slate-500">Examples</p><p class="mt-1 text-sm">{{ implode(', ', $classification['examples']) }}</p><p class="mt-3 text-xs font-semibold uppercase text-slate-500">Controls</p><p class="mt-1 text-sm">{{ implode(', ', $classification['controls']) }}</p></article>@endforeach</section>

    <section class="mt-6 rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="font-semibold">Data-subject lookup</h2><p class="text-sm text-slate-600">Minimum three characters. Results remain masked without sensitive-data permission.</p></div>@can('sensitive-data.export') @if(filled($term))<a href="{{ route('privacy.data-subjects.export', ['q' => $term]) }}" class="rounded-lg bg-blue-700 px-4 py-2 text-sm font-semibold text-white">Export authorized results</a>@endif @endcan</div><form method="GET" class="mt-4 flex flex-wrap gap-3"><input name="q" value="{{ $term }}" minlength="3" maxlength="120" placeholder="Name, email, or TIN" class="min-w-64 flex-1 rounded-lg border border-slate-300 px-3 py-2"><button class="rounded-lg border border-blue-700 px-4 py-2 text-sm font-semibold text-blue-700">Search</button></form>
        @if(filled($term))<div class="mt-4 overflow-x-auto"><table class="min-w-full text-sm"><thead><tr><th class="px-3 py-2 text-left">Type</th><th class="px-3 py-2 text-left">Name</th><th class="px-3 py-2 text-left">Email / phone</th><th class="px-3 py-2 text-left">Address</th><th class="px-3 py-2 text-left">TIN</th><th class="px-3 py-2 text-left">Archive</th></tr></thead><tbody class="divide-y divide-slate-200">@forelse($results as $row)<tr><td class="px-3 py-2 capitalize">{{ $row['type'] }}</td><td class="px-3 py-2">{{ $row['name'] }}</td><td class="px-3 py-2">{{ $row['email'] }}<br>{{ $row['phone'] }}</td><td class="px-3 py-2">{{ $row['address'] }}</td><td class="px-3 py-2 font-mono">{{ $row['tin'] }}</td><td class="px-3 py-2">@if(in_array($row['type'], ['customer', 'supplier'], true)) @can('records.archive')<form method="POST" action="{{ route('privacy.archive', [$row['type'], $row['id']]) }}" class="flex gap-2">@csrf<input name="reason" required minlength="10" placeholder="Archive reason" class="w-40 rounded border border-slate-300 px-2 py-1"><button class="text-sm font-semibold text-blue-700">Archive</button></form>@endcan @else — @endif</td></tr>@empty<tr><td colspan="6" class="px-3 py-6 text-center text-slate-500">No matching records.</td></tr>@endforelse</tbody></table></div>@endif
    </section>

    <section class="mt-6 rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 class="font-semibold">Retention policies</h2><p class="text-sm text-slate-600">Expiry creates a review point only. This screen never automatically purges records.</p><div class="mt-4 overflow-x-auto"><table class="min-w-full text-sm"><thead><tr><th class="px-3 py-2 text-left">Record type</th><th class="px-3 py-2 text-left">Class</th><th class="px-3 py-2 text-left">Period</th><th class="px-3 py-2 text-left">Trigger</th><th class="px-3 py-2 text-left">Disposition</th><th class="px-3 py-2 text-left">Reviewed</th></tr></thead><tbody class="divide-y divide-slate-200">@foreach($policies as $policy)<tr><td class="px-3 py-2">{{ str($policy->record_type)->headline() }}</td><td class="px-3 py-2 capitalize">{{ $policy->classification }}</td><td class="px-3 py-2">{{ $policy->retention_months ? $policy->retention_months.' months' : 'Permanent' }}</td><td class="px-3 py-2">{{ str($policy->retention_trigger)->headline() }}</td><td class="px-3 py-2">{{ str($policy->disposition)->headline() }}</td><td class="px-3 py-2">{{ $policy->reviewed_at->format('M d, Y') }}</td></tr>@endforeach</tbody></table></div>
        @can('privacy-settings.manage')<form method="POST" action="{{ route('privacy.retention-policies.store') }}" class="mt-5 grid gap-3 md:grid-cols-2 lg:grid-cols-4">@csrf<input name="record_type" required placeholder="Record type key" class="rounded-lg border border-slate-300 px-3 py-2"><select name="classification" required class="rounded-lg border border-slate-300 px-3 py-2">@foreach(array_keys($classifications) as $level)<option>{{ $level }}</option>@endforeach</select><input type="number" name="retention_months" min="1" max="1200" placeholder="Months (blank if permanent)" class="rounded-lg border border-slate-300 px-3 py-2"><input name="retention_trigger" required placeholder="Retention trigger" class="rounded-lg border border-slate-300 px-3 py-2"><select name="disposition" required class="rounded-lg border border-slate-300 px-3 py-2"><option value="review_for_disposal">Review for disposal</option><option value="archive">Archive</option><option value="anonymize">Anonymize</option><option value="retain_permanently">Retain permanently</option></select><input type="date" name="reviewed_at" value="{{ now()->toDateString() }}" required class="rounded-lg border border-slate-300 px-3 py-2"><input type="hidden" name="active" value="1"><textarea name="legal_basis" required minlength="10" placeholder="Legal or business basis" class="rounded-lg border border-slate-300 px-3 py-2 lg:col-span-2"></textarea><button class="rounded-lg bg-blue-700 px-4 py-2 text-sm font-semibold text-white">Save policy</button></form>@endcan
    </section>
</x-app-layout>
