<x-app-layout title="Cash Position">
    <x-page-header title="Cash Position and Activity" description="Read-only operational cash and banking activity from posted Phase 5 transactions." />
    <nav class="mb-5 flex flex-wrap gap-3 text-sm"><a href="{{ route('cash-reports.print', request()->query()) }}">Print</a>@can('cash-reports.export')<a href="{{ route('cash-reports.export', request()->query()) }}">CSV export</a>@endcan</nav>
    <form method="GET" action="{{ route('cash-reports.index') }}" class="mb-6 grid gap-4 rounded-xl bg-white p-4 ring-1 ring-slate-200 sm:grid-cols-2 lg:grid-cols-6">
        <label class="grid gap-1 text-sm">Start<input type="date" name="start_date" value="{{ $filters['start_date'] }}" class="rounded-lg border-slate-300"></label>
        <label class="grid gap-1 text-sm">End<input type="date" name="end_date" value="{{ $filters['end_date'] }}" class="rounded-lg border-slate-300"></label>
        <label class="grid gap-1 text-sm">As of<input type="date" name="as_of" value="{{ $filters['as_of'] }}" class="rounded-lg border-slate-300">@error('as_of')<span class="text-red-600">{{ $message }}</span>@enderror</label>
        <label class="grid gap-1 text-sm">Account<select name="financial_account_id" class="rounded-lg border-slate-300"><option value="">All</option>@foreach($accounts as $account)<option value="{{ $account->id }}" @selected($filters['financial_account_id'] == $account->id)>{{ $account->code }} — {{ $account->name }}</option>@endforeach</select></label>
        <label class="grid gap-1 text-sm">Account type<select name="account_type" class="rounded-lg border-slate-300"><option value="">All</option>@foreach($accountTypes as $type)<option value="{{ $type->value }}" @selected($filters['account_type'] === $type->value)>{{ str($type->value)->headline() }}</option>@endforeach</select></label>
        <label class="grid gap-1 text-sm">Transaction type<select name="transaction_type" class="rounded-lg border-slate-300"><option value="">All</option>@foreach($transactionTypes as $type)<option value="{{ $type->value }}" @selected($filters['transaction_type'] === $type->value)>{{ str($type->value)->headline() }}</option>@endforeach</select></label>
        <button class="w-fit rounded-lg bg-blue-700 px-4 py-2 text-sm font-semibold text-white">Apply filters</button>
    </form>
    <div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">
        @foreach(['Receipts' => $report['receipts'], 'Disbursements' => $report['disbursements'], 'Net movement' => $report['net_movement'], 'Reconciled activity' => $report['reconciled'], 'Unreconciled activity' => $report['unreconciled']] as $label => $value)<div class="rounded-xl bg-white p-4 ring-1 ring-slate-200"><div class="text-xs text-slate-500">{{ $label }}</div><div class="text-lg font-semibold">PHP {{ number_format((float) $value, 2) }}</div></div>@endforeach
    </div>
    <h2 class="mt-7 text-lg font-semibold">Account balances</h2>
    <div class="mt-3 overflow-x-auto rounded-xl bg-white ring-1 ring-slate-200"><table class="min-w-full text-sm"><thead><tr><th class="px-4 py-3 text-left">Account</th><th>Type</th><th class="text-right">Opening</th><th class="text-right">Movement</th><th class="text-right">Closing</th><th class="text-right">As-of position</th></tr></thead><tbody>@foreach($report['positions'] as $position)<tr class="border-t"><td class="px-4 py-3">{{ $position['account']->code }} — {{ $position['account']->name }}</td><td class="text-center">{{ str($position['account']->type->value)->headline() }}</td><td class="text-right">{{ number_format((float) $position['opening'], 2) }}</td><td class="text-right">{{ number_format((float) $position['movement'], 2) }}</td><td class="text-right">{{ number_format((float) $position['closing'], 2) }}</td><td class="text-right font-semibold">{{ number_format((float) $position['as_of'], 2) }}</td></tr>@endforeach</tbody></table></div>
    <div class="mt-7 grid gap-6 lg:grid-cols-2">
        <section><h2 class="text-lg font-semibold">Daily receipts and disbursements</h2><div class="mt-3 rounded-xl bg-white p-4 ring-1 ring-slate-200">@forelse($report['daily_movements'] as $date => $daily)<div class="flex justify-between gap-4 border-b py-2 text-sm"><span>{{ $date }}</span><span>In {{ number_format((float) $daily['receipts'], 2) }} · Out {{ number_format((float) $daily['disbursements'], 2) }}</span></div>@empty<p>No daily activity.</p>@endforelse</div></section>
        <section><h2 class="text-lg font-semibold">Movement by source type</h2><div class="mt-3 rounded-xl bg-white p-4 ring-1 ring-slate-200">@forelse($report['source_movements'] as $type => $amount)<div class="flex justify-between gap-4 border-b py-2 text-sm"><span>{{ str($type)->headline() }}</span><span>{{ number_format((float) $amount, 2) }}</span></div>@empty<p>No movement.</p>@endforelse</div></section>
        <section><h2 class="text-lg font-semibold">Transfers in transit</h2><div class="mt-3 rounded-xl bg-white p-4 ring-1 ring-slate-200">@forelse($report['transfers_in_transit'] as $transfer)<div class="border-b py-2 text-sm">{{ $transfer->transfer_number }} · {{ $transfer->sourceFinancialAccount->code }} → {{ $transfer->destinationFinancialAccount->code }} · {{ number_format((float) $transfer->amount, 2) }}</div>@empty<p>No transfers in transit.</p>@endforelse</div></section>
        <section><h2 class="text-lg font-semibold">Petty-cash activity</h2><div class="mt-3 rounded-xl bg-white p-4 ring-1 ring-slate-200">@forelse($report['petty_cash_activity'] as $transaction)<div class="border-b py-2 text-sm">{{ $transaction->transaction_date->toDateString() }} · {{ str($transaction->type->value)->headline() }} · {{ number_format((float) $transaction->amount, 2) }}</div>@empty<p>No petty-cash activity.</p>@endforelse</div></section>
        @if($canViewReconciliation)<section><h2 class="text-lg font-semibold">Unreconciled statement items</h2><div class="mt-3 rounded-xl bg-white p-4 ring-1 ring-slate-200">@forelse($report['unreconciled_items'] as $line)<div class="border-b py-2 text-sm">{{ $line->transaction_date->toDateString() }} · {{ $line->bankStatementImport->financialAccount->code }} · {{ $line->description }} · {{ number_format((float) $line->normalized_amount, 2) }}</div>@empty<p>No unreconciled items.</p>@endforelse</div></section>
        <section><h2 class="text-lg font-semibold">Reconciliation history</h2><div class="mt-3 rounded-xl bg-white p-4 ring-1 ring-slate-200">@forelse($report['reconciliation_history'] as $reconciliation)<div class="border-b py-2 text-sm">{{ $reconciliation->statement_end_date->toDateString() }} · {{ $reconciliation->financialAccount->code }} · {{ $reconciliation->status->value }} · Difference {{ number_format((float) $reconciliation->reconciliation_difference, 2) }}</div>@empty<p>No reconciliation history.</p>@endforelse</div></section>@endif
    </div>
    <h2 class="mt-7 text-lg font-semibold">Posted activity</h2>
    <div class="mt-3 overflow-x-auto rounded-xl bg-white ring-1 ring-slate-200"><table class="min-w-full text-sm"><thead><tr><th class="px-4 py-3">Date</th><th>Account</th><th>Type</th><th>Reference</th><th class="text-right">Amount</th><th>Reconciliation</th></tr></thead><tbody>@forelse($activity as $transaction)<tr class="border-t"><td class="px-4 py-3 text-center">{{ $transaction->transaction_date->toDateString() }}</td><td class="text-center">{{ $transaction->financialAccount->code }}</td><td class="text-center">{{ str($transaction->type->value)->headline() }}</td><td class="text-center">{{ $transaction->reference_number ?? '—' }}</td><td class="text-right">{{ number_format((float) $transaction->amount, 2) }}</td><td class="text-center">{{ $transaction->reconciliation_match_exists ? 'Reconciled' : 'Unreconciled' }}</td></tr>@empty<tr><td colspan="6" class="p-8 text-center">No posted activity for this range.</td></tr>@endforelse</tbody></table></div>
    <div class="mt-5">{{ $activity->links() }}</div>
</x-app-layout>
